import { mount } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'
import { createRouter, createMemoryHistory } from 'vue-router'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { useProjectStore } from '@/modules/projects/projectStore'
import StudioPage from './StudioPage.vue'
vi.mock('vant',async()=>({...await vi.importActual('vant'),showConfirmDialog:vi.fn(()=>Promise.resolve())}))
beforeEach(()=>localStorage.clear())
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();vi.useRealTimers()})
async function setup(){const pinia=createPinia();setActivePinia(pinia);const store=useProjectStore(),p=store.create();const cells=[...p.cells];cells[0]='H7';cells[1]='H7';cells[3]='H2';store.update({...p,cells,layers:[{...p.layers[0],cells}]});const router=createRouter({history:createMemoryHistory(),routes:[{path:'/studio/:id',component:StudioPage}]});await router.push(`/studio/${p.id}`);const w=mount(StudioPage,{global:{plugins:[pinia,router],stubs:{BeadCanvas:{name:'BeadCanvas',props:['tool','color','width','height','cells'],template:'<div/>',methods:{cancel:vi.fn(),fit:vi.fn(),endPreview:vi.fn()}}}}});return {w,store}}
async function button(w:Awaited<ReturnType<typeof setup>>['w'],text:string){const b=w.findAll('button').find(b=>b.attributes('aria-label')===text||b.text()===text||b.text().includes(text));expect(b, text).toBeTruthy();await b!.trigger('click')}
describe('focused editor sessions',()=>{
 it('sorts usage counts in both directions and labels units in the header',async()=>{const {w}=await setup();await button(w,'用量');expect(w.find('.pin-usage-head').text()).toContain('色号');expect(w.find('.pin-usage-head').text()).toContain('颗数消耗');expect(w.find('.pin-usage-head').text()).toContain('包消耗');const rows=()=>w.findAll('.pin-usage [role="row"]').slice(1).map(row=>row.findAll('[role="cell"]').map(c=>c.text()));expect(rows()).toEqual([['H2','1','1'],['H7','2','1']]);await button(w,'按颗数升序排列');expect(rows()).toEqual([['H2','1','1'],['H7','2','1']]);await button(w,'按颗数降序排列');expect(rows()[0]).toEqual(['H7','2','1']);await button(w,'按色号排列');expect(rows()[0]).toEqual(['H2','1','1']);w.unmount()})
 it('holds brush changes until confirmation and discards on cancel',async()=>{const {w,store}=await setup();await button(w,'画笔');const c=[...store.current!.cells];c[4]='A1';w.findComponent({name:'BeadCanvas'}).vm.$emit('change',c);await w.vm.$nextTick();expect(store.current!.cells[4]).toBeNull();await button(w,'取消当前操作');expect(store.current!.cells[4]).toBeNull();await button(w,'画笔');w.findComponent({name:'BeadCanvas'}).vm.$emit('change',c);await w.vm.$nextTick();await button(w,'保存当前操作');expect(store.current!.cells[4]).toBe('A1');w.unmount()})
 it('undoes individual strokes inside a session and the entire saved session outside',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'画笔');expect(w.find('.pin-peek').exists()).toBe(false);const board=w.findComponent({name:'BeadCanvas'}),a=[...original];a[4]='A1';board.vm.$emit('change',a);await w.vm.$nextTick();const b=[...a];b[5]='A2';board.vm.$emit('change',b);await w.vm.$nextTick();await button(w,'撤销');await button(w,'重做');expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');expect(store.current!.cells).toEqual(b);expect(w.find('.pin-peek').exists()).toBe(true);await button(w,'撤销');expect(store.current!.cells).toEqual(original);await button(w,'重做');expect(store.current!.cells).toEqual(b);await button(w,'画笔');expect(w.find('[aria-label="撤销"]').attributes('disabled')).toBeDefined();await button(w,'取消当前操作');w.unmount()})
 it('composes mirror clicks and commits the displayed result',async()=>{const {w,store}=await setup();await button(w,'编辑');await button(w,'水平镜像');await button(w,'垂直镜像');expect(store.current!.cells[0]).toBeNull();expect(store.current!.cells.at(-1)).toBe('H7');w.unmount()})
 it('mirrors directly and cycles grid and bead shape from the edit menu',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'编辑');await button(w,'水平镜像');await button(w,'水平镜像');expect(store.current!.cells).toEqual(original);expect(w.find('.pin-mode-dock').exists()).toBe(false);await button(w,'自动网格');expect(store.current!.settings?.grid).toBe('off');await button(w,'隐藏网格');expect(store.current!.settings?.grid).toBe('always');await button(w,'显示网格');expect(store.current!.settings?.grid).toBe('auto');await button(w,'方豆');expect(store.current!.settings?.round).toBe(true);expect(w.text()).not.toContain('减少用色');w.unmount()})

 it('enters selection before drawing and keeps selection edits in local history',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'选区');expect(w.text()).toContain('拖出范围');expect(w.find('.pin-categories').exists()).toBe(false);const board=w.findComponent({name:'BeadCanvas'});board.vm.$emit('select',{x:0,y:0,width:2,height:1});await w.vm.$nextTick();await button(w,'擦除');expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');expect(store.current!.cells[0]).toBeNull();await button(w,'撤销');expect(store.current!.cells).toEqual(original);w.unmount()})
 it('starts erasing with empty history even after a prior saved brush session',async()=>{const {w,store}=await setup();await button(w,'画笔');const board=w.findComponent({name:'BeadCanvas'}),c=[...store.current!.cells];c[7]='H7';board.vm.$emit('change',c);await w.vm.$nextTick();await button(w,'保存当前操作');await button(w,'橡皮');expect(w.find('[aria-label="撤销"]').attributes('disabled')).toBeDefined();const erased=[...c];erased[7]=null;board.vm.$emit('change',erased);await w.vm.$nextTick();await button(w,'保存当前操作');await button(w,'撤销');expect(store.current!.cells[7]).toBe('H7');w.unmount()})
 it('imports directly into a fixed canvas and applies a padded preview',async()=>{vi.spyOn(HTMLCanvasElement.prototype,'toDataURL').mockReturnValue('data:image/png;base64,cropped');vi.useFakeTimers();vi.stubGlobal('Image',class{onload:()=>void=()=>{};naturalWidth=8;naturalHeight=8;set src(_:string){this.onload()}});vi.stubGlobal('Worker',class{onmessage:(e:unknown)=>void=()=>{};onerror=()=>{};terminate(){};postMessage(data:{id:number;width:number;height:number}){this.onmessage({data:{id:data.id,cells:Array(data.width*data.height).fill('H7')}})}});vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue({drawImage:vi.fn(),getImageData:()=>({data:new Uint8ClampedArray(52*52*9*4)})} as unknown as CanvasRenderingContext2D);URL.createObjectURL=vi.fn(()=>'blob:test');URL.revokeObjectURL=vi.fn();const {w,store}=await setup(),original=[...store.current!.cells];const file=w.find('input[type="file"]');Object.defineProperty(file.element,'files',{value:[new File(['photo'],'test.png',{type:'image/png'})]});await file.trigger('change');expect(w.text()).not.toContain('选择图片类型');expect(w.text()).not.toContain('我的豆色');expect(w.find('.pin-crop-overlay').exists()).toBe(false);expect(w.text()).toContain('32 × 32');expect(w.text()).toContain('100 × 100');await button(w,'52 × 52');expect(w.text()).not.toContain('去除背景');expect(w.text()).not.toContain('保留背景');expect(w.text()).not.toContain('修整豆子');expect(w.text()).not.toContain('整体预览');expect(w.text()).not.toContain('用色上限');expect(w.find('[aria-label="导入照片功能"]').findAll('button').map(b=>b.text())).toEqual(['旋转','图案大小','图片类型']);expect(w.find('.pin-placement-frame').exists()).toBe(true);expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');await vi.advanceTimersByTimeAsync(350);await w.vm.$nextTick();expect(w.text()).toContain('图纸预览');expect(w.find('.pin-summary').exists()).toBe(false);expect(w.text()).not.toContain('修整豆子');expect(w.text()).not.toContain('整体预览');expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');await w.vm.$nextTick();expect(w.text()).not.toContain('图纸预览');expect(store.current!.width).toBe(54);expect(store.current!.height).toBe(54);expect(store.current!.cells.filter(Boolean)).toHaveLength(52*52);expect(store.current!.cells.slice(0,54).every(cell=>cell===null)).toBe(true);expect(store.current!.cells[55]).toBe('H7');expect(store.current!.settings?.reference).toEqual({url:'data:image/png;base64,cropped',opacity:.35,scale:52/54,x:1,y:1});await button(w,'编辑');await button(w,'参考图');expect(w.find('[aria-label="参考图透明度"]').exists()).toBe(true);expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe('pan');await button(w,'取消当前操作');await button(w,'撤销');expect(store.current!.cells).toEqual(original);w.unmount()})
 it('retains the target across source colors and saves the whole replacement session once',async()=>{const {w,store}=await setup();const p=store.current!,cells=[...p.cells];cells[4]='A1';store.update({...p,cells,layers:[{...p.layers[0],cells}]});await button(w,'换色');const board=w.findComponent({name:'BeadCanvas'});board.vm.$emit('focus',0);await w.vm.$nextTick();w.findComponent({name:'ColorDock'}).vm.$emit('pick');await w.vm.$nextTick();board.vm.$emit('pick','H2');await w.vm.$nextTick();board.vm.$emit('focus',4);await w.vm.$nextTick();expect(w.findComponent({name:'ColorDock'}).props('color')).toBe('H2');expect(board.props('cells').slice(0,5)).toEqual(['H2','H2',null,'H2','H2']);expect(store.current!.cells).toEqual(cells);await button(w,'撤销');expect(board.props('cells')[4]).toBe('A1');await button(w,'重做');expect(board.props('cells')[4]).toBe('H2');await button(w,'保存当前操作');expect(store.current!.cells.slice(0,5)).toEqual(['H2','H2',null,'H2','H2']);await button(w,'撤销');expect(store.current!.cells).toEqual(cells);w.unmount()})
 it('picks a replacement color without changing the source selection and supports undo',async()=>{const {w,store}=await setup();await button(w,'换色');const board=w.findComponent({name:'BeadCanvas'});board.vm.$emit('focus',0);await w.vm.$nextTick();const dock=w.findComponent({name:'ColorDock'});expect(dock.props('canPick')).toBe(true);dock.vm.$emit('pick');await w.vm.$nextTick();expect(board.props('tool')).toBe('eyedropper');board.vm.$emit('pick','H2');await w.vm.$nextTick();expect(dock.props('color')).toBe('H2');expect(board.props('tool')).toBe('recolor');expect(store.current!.cells[0]).toBe('H7');await button(w,'撤销');expect(dock.props('color')).toBe('H7');await button(w,'重做');expect(dock.props('color')).toBe('H2');await button(w,'保存当前操作');expect(store.current!.cells.slice(0,4)).toEqual(['H2','H2',null,'H2']);w.unmount()})
 it('selects source beads before replacing and supports a palette replacement',async()=>{const {w,store}=await setup();await button(w,'换色');expect(w.text()).toContain('先点选豆板');const board=w.findComponent({name:'BeadCanvas'});board.vm.$emit('focus',0);await w.vm.$nextTick();await w.findComponent({name:'ColorDock'}).vm.$emit('choose','H2');await w.vm.$nextTick();expect(store.current!.cells[0]).toBe('H7');await button(w,'保存当前操作');expect(store.current!.cells.slice(0,4)).toEqual(['H2','H2',null,'H2']);w.unmount()})
 it('restores brush and fill after choosing a palette color while picking',async()=>{const {w}=await setup();for(const label of ['画笔','填充']){await button(w,label);const dock=w.findComponent({name:'ColorDock'});dock.vm.$emit('pick');await w.vm.$nextTick();expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe('eyedropper');dock.vm.$emit('choose','A5');await w.vm.$nextTick();expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe(label==='画笔'?'pencil':'fill');expect(w.findComponent({name:'BeadCanvas'}).props('color')).toBe('A5');await button(w,'取消当前操作')}w.unmount()})

 it('undoes replacement choices and toggles original without committing',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'换色');w.findComponent({name:'BeadCanvas'}).vm.$emit('focus',0);await w.vm.$nextTick();const dock=w.findComponent({name:'ColorDock'});dock.vm.$emit('choose','A1');await w.vm.$nextTick();dock.vm.$emit('choose','A2');await w.vm.$nextTick();await button(w,'撤销');expect(dock.props('color')).toBe('A1');await button(w,'重做');expect(dock.props('color')).toBe('A2');await w.find('.pin-recolor-compare').trigger('keydown',{key:' '});expect(w.find('.pin-recolor-compare').attributes('aria-pressed')).toBe('true');expect(store.current!.cells).toEqual(original);await w.find('.pin-recolor-compare').trigger('keyup',{key:' '});await button(w,'保存当前操作');expect(store.current!.cells[0]).toBe('A2');w.unmount()})

 it('previews typed width and height independently before saving',async()=>{const {w,store}=await setup();await button(w,'编辑');await button(w,'豆板尺寸');await w.find('[aria-label="豆板宽度"]').setValue('80');await w.find('[aria-label="豆板高度"]').setValue('60');const board=w.findComponent({name:'BeadCanvas'});expect(board.props('width')).toBe(80);expect(board.props('height')).toBe(60);expect(store.current!.width).toBe(52);expect(store.current!.height).toBe(52);await button(w,'保存当前操作');expect(store.current!.width).toBe(80);expect(store.current!.height).toBe(60);w.unmount()})
 it('previews centered board resizing without changing saved data until confirmation',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'编辑');await button(w,'豆板尺寸');await button(w,'100 × 100');const board=w.findComponent({name:'BeadCanvas'});expect(board.props('width')).toBe(100);expect(board.props('height')).toBe(100);expect(board.props('cells')[24*100+24]).toBe('H7');expect(store.current!.width).toBe(52);expect(store.current!.cells).toEqual(original);await button(w,'取消当前操作');expect(board.props('width')).toBe(52);await button(w,'豆板尺寸');await button(w,'100 × 100');w.findComponent({name:'BoardPlacement'}).vm.$emit('update:modelValue',{x:20,y:22});await w.vm.$nextTick();expect(board.props('cells')[22*100+20]).toBe('H7');expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');expect(store.current!.width).toBe(100);expect(store.current!.cells[22*100+20]).toBe('H7');w.unmount()})
 it('confirms clearing directly without entering an editing mode',async()=>{const {w,store}=await setup();await button(w,'编辑');await button(w,'清空');await w.vm.$nextTick();expect(w.find('.pin-mode-dock').exists()).toBe(false);expect(store.current!.cells.filter(Boolean)).toHaveLength(0);await button(w,'撤销');expect(store.current!.cells[0]).toBe('H7');w.unmount()})

 it('toggles the eraser inside a brush session and restores brush on color selection',async()=>{const {w}=await setup();await button(w,'画笔');const dock=w.findComponent({name:'ColorDock'});expect(dock.props('canErase')).toBe(true);dock.vm.$emit('erase');await w.vm.$nextTick();expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe('eraser');dock.vm.$emit('choose','A3');await w.vm.$nextTick();expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe('pencil');w.unmount()})

})
