<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Icon as VanIcon, Popup as VanPopup, showConfirmDialog, showToast } from 'vant'
import AppShell from '@/shared/AppShell.vue'
import { colorByCode, palette, type ProjectLayer, type Tool } from '@/core/project'
import { useProjectStore } from '@/modules/projects/projectStore'
import BeadCanvas from '../BeadCanvas.vue'
import MiniPreview from '../MiniPreview.vue'
import ToolGlyph from '../ToolGlyph.vue'
import LockGlyph from '../LockGlyph.vue'

const route=useRoute(),router=useRouter(),store=useProjectStore();store.open(String(route.params.id));const rawProject=computed(()=>store.current)
const layers=computed(()=>rawProject.value?.layers??[])
const activeLayer=computed(()=>layers.value.find(layer=>layer.id===rawProject.value?.activeLayerId)??layers.value.find(layer=>layer.type==='bead')??null)
const project=computed(()=>rawProject.value&&activeLayer.value?.type==='bead'?{...rawProject.value,cells:activeLayer.value.cells}:rawProject.value)
const tool=ref<Tool>('pan'),color=ref('H7'),grid=ref(true),coordinates=ref(false),round=ref(false),zoom=ref(1),boardTone=ref<'light'|'dark'>('light')
const panel=ref<'usage'|'adjust'>('adjust'),paletteGroup=ref('H'),panelOpen=ref(window.innerWidth>820),paletteExpanded=ref(false),widthDraft=ref(52),heightDraft=ref(52)
const resizeOpen=ref(false),ratioLocked=ref(true),resizeOffsetX=ref(0),resizeOffsetY=ref(0),opacityBubble=ref<number|null>(null)
const selectedPreset=ref('')
const openToolGroup=ref<'draw'|'select'|'view'|null>(null)
const beadLayerVisible=ref(true),beadLayerLocked=ref(false)
const layerMenuId=ref<string|null>(null),newLayerMenu=ref(false),draggedLayerId=ref<string|null>(null),referenceInput=ref<HTMLInputElement|null>(null)
const layersOpen=ref(false)
const recolorMode=ref<'single'|'same'>('single')
const returnToolAfterPick=ref<Tool|null>(null),focusedIndex=ref<number|null>(null),previewOpen=ref(false)
const menuLayer=computed(()=>layers.value.find(layer=>layer.id===layerMenuId.value)??null)
const layerSheetOpen=computed({get:()=>Boolean(layerMenuId.value),set:(show:boolean)=>{if(!show)layerMenuId.value=null}})
const importMenuOpen=ref(false),pendingImageUrl=ref(''),pendingImageName=ref(''),convertWidth=ref(52),maxColors=ref(24),generationStyle=ref<'cartoon'|'realistic'>('cartoon'),backgroundMode=ref<'keep'|'remove'>('keep'),backgroundTolerance=ref(32),generatedLayerName=ref('')
const cropAspect=ref<'1:1'|'4:3'|'3:4'|'original'>('1:1'),cropZoom=ref(1),cropX=ref(0),cropY=ref(0)
const importDraft=ref<{width:number;height:number;cells:Array<string|null>;colors:number}|null>(null)
let cropDragging=false,cropPointerX=0,cropPointerY=0,resizeDragging=false,resizePointerX=0,resizePointerY=0
type CanvasSnapshot={width:number;height:number;cells:Array<string|null>}
const history=ref<CanvasSnapshot[]>([]),future=ref<CanvasSnapshot[]>([]),clipboard=ref<{width:number;height:number;cells:Array<string|null>}|null>(null),pendingMove=ref<{ids:number[];width:number;height:number;cells:Array<string|null>}|null>(null),fileInput=ref<HTMLInputElement|null>(null)
const groups=['All','A','B','C','D','E','F','G','H','M'];const filteredPalette=computed(()=>palette.filter(c=>paletteGroup.value==='All'||c.code.startsWith(paletteGroup.value)))
const visibleCells=computed(()=>rawProject.value?composedCells(layers.value):[])
const usage=computed(()=>palette.map(c=>({color:c,count:visibleCells.value.filter(x=>x===c.code).length})).filter(x=>x.count).sort((a,b)=>b.count-a.count))
const recommendedColors=computed(()=>{if(focusedIndex.value===null||!project.value)return[];const index=focusedIndex.value,target=project.value.cells[index],targetColor=colorByCode(target||'')??colorByCode(color.value),x=index%project.value.width,y=Math.floor(index/project.value.width),near=[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[1,-1],[-1,1],[1,1]].map(([dx,dy])=>{const nx=x+dx,ny=y+dy;return nx>=0&&ny>=0&&nx<project.value!.width&&ny<project.value!.height?project.value!.cells[ny*project.value!.width+nx]:null}).filter((code):code is string=>Boolean(code)),unique=[...new Set(near)].map(code=>colorByCode(code)).filter(Boolean);if(targetColor){const rgb=rgbOf(targetColor.hex);palette.slice().sort((a,b)=>distance(rgb,rgbOf(a.hex))-distance(rgb,rgbOf(b.hex))).forEach(item=>{if(item.code!==target&&!unique.some(value=>value?.code===item.code)&&unique.length<8)unique.push(item)})}return unique.slice(0,8) as typeof palette})
const tools:{id:Tool;label:string}[]=[{id:'pencil',label:'画笔'},{id:'eraser',label:'橡皮擦'},{id:'fill',label:'矩形填充'},{id:'remove',label:'矩形消除'},{id:'recolor',label:'换色'},{id:'eyedropper',label:'吸管取色'},{id:'move',label:'移动选区'},{id:'copy',label:'复制选区'},{id:'paste',label:'粘贴'},{id:'shape',label:'形状'},{id:'text',label:'文字'},{id:'pan',label:'拖动画布'}]
const drawToolIds:Tool[]=['pencil','eraser','fill','remove','recolor','text'],selectToolIds:Tool[]=['move','copy','paste']
function activateTool(next:Tool){if(next==='eyedropper'&&tool.value!=='eyedropper')returnToolAfterPick.value=tool.value;else if(next!=='eyedropper')returnToolAfterPick.value=null;tool.value=next;openToolGroup.value=null;if(next!=='move')pendingMove.value=null}
function toggleToolGroup(group:'draw'|'select'){const opening=openToolGroup.value!==group;openToolGroup.value=opening?group:null;if(opening){tool.value='pan';pendingMove.value=null}}
function toggleImport(){openToolGroup.value=null;paletteExpanded.value=false;tool.value='pan';pendingMove.value=null;if(pendingImageUrl.value)importMenuOpen.value=!importMenuOpen.value;else selectImage()}
function handleOutside(event:PointerEvent){const target=event.target as HTMLElement;if(target.closest('.tool-group,.bottom-palette,.recolor-mode-bar,.canvas-area,.import-config-popover'))return;if(openToolGroup.value||importMenuOpen.value||paletteExpanded.value)closeTransient()}
function toolHint(id:Tool){if(id==='pencil')return'逐格绘制';if(id==='eraser')return'擦除经过的单个格子';if(id==='fill')return'沿对角线拖出并填满矩形区域';if(id==='remove')return'沿对角线拖出要清除的矩形区域';if(id==='recolor')return'替换单豆或相同色号';if(id==='shape')return'沿对角线拖出实心矩形';if(id==='text')return'将文字转换为拼豆';return'修改画布内容'}
function renameCurrent(){if(!rawProject.value)return;const name=window.prompt('重命名图纸',rawProject.value.name)?.trim();if(name)store.update({...rawProject.value,name})}
function snapshot():CanvasSnapshot{return{width:project.value!.width,height:project.value!.height,cells:[...project.value!.cells]}}
function composedCells(source:ProjectLayer[],width=rawProject.value!.width,height=rawProject.value!.height){const result=Array<string|null>(width*height).fill(null);source.filter(layer=>layer.type==='bead'&&layer.visible).forEach(layer=>layer.cells.forEach((cell,index)=>{if(cell)result[index]=cell}));return result}
function saveLayers(next:ProjectLayer[],activeId=rawProject.value!.activeLayerId,width=rawProject.value!.width,height=rawProject.value!.height){if(!rawProject.value)return;store.update({...rawProject.value,width,height,layers:next,activeLayerId:activeId,cells:composedCells(next,width,height)})}
function updateActiveCells(cells:Array<string|null>){if(!activeLayer.value||activeLayer.value.type!=='bead')return;const next=layers.value.map(layer=>layer.id===activeLayer.value!.id?{...layer,cells}:layer);saveLayers(next)}
function restore(value:CanvasSnapshot){if(!project.value||!activeLayer.value)return;const next=layers.value.map(layer=>layer.id===activeLayer.value!.id?{...layer,cells:[...value.cells]}:{...layer,cells:resizeCells(layer.cells,rawProject.value!.width,rawProject.value!.height,value.width,value.height)});saveLayers(next,activeLayer.value.id,value.width,value.height);widthDraft.value=value.width;heightDraft.value=value.height;selectedPreset.value=[52,78,104,156].includes(value.width)&&value.width===value.height?`${value.width}x${value.height}`:''}
function pushHistory(value:CanvasSnapshot){history.value=[...history.value.slice(-39),value]}
function change(cells:Array<string|null>,record=true){if(!project.value||activeLayer.value?.locked)return;if(record){pushHistory(snapshot());future.value=[]}updateActiveCells(cells)}
function undo(){if(!project.value||!history.value.length)return;const previous=history.value[history.value.length-1];future.value=[...future.value,snapshot()];history.value=history.value.slice(0,-1);restore(previous)}function redo(){if(!project.value||!future.value.length)return;const next=future.value[future.value.length-1];pushHistory(snapshot());future.value=future.value.slice(0,-1);restore(next)}
function pick(code:string){color.value=code;const resume=returnToolAfterPick.value;tool.value=resume==='recolor'?'recolor':resume&&resume!=='pan'?resume:'pencil';returnToolAfterPick.value=null;showToast(resume==='recolor'?`已吸取 ${code}，继续换色`:`已选择 ${code}`)}
function focusBead(index:number){focusedIndex.value=index;const code=project.value?.cells[index];if(code)showToast(`已聚焦 ${code}，可选择推荐色替换`)}
function chooseRecommended(code:string){color.value=code;if(tool.value==='recolor'&&focusedIndex.value!==null&&project.value){const next=[...project.value.cells],target=next[focusedIndex.value];if(recolorMode.value==='same'&&target)next.forEach((value,index)=>{if(value===target)next[index]=code});else next[focusedIndex.value]=code;change(next);showToast(`已替换为 ${code}`)}else tool.value='recolor'}
function connected(start:number){if(!project.value)return[];const cells=project.value.cells,q=[start],seen=new Set<number>();while(q.length){const i=q.pop()!;if(seen.has(i)||!cells[i])continue;seen.add(i);const x=i%project.value.width;if(x)q.push(i-1);if(x<project.value.width-1)q.push(i+1);if(i>=project.value.width)q.push(i-project.value.width);if(i<cells.length-project.value.width)q.push(i+project.value.width)}return[...seen]}
function regionPattern(ids:number[]){const xs=ids.map(i=>i%project.value!.width),ys=ids.map(i=>Math.floor(i/project.value!.width)),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),w=maxX-minX+1,h=maxY-minY+1,cells=Array<string|null>(w*h).fill(null);ids.forEach(i=>cells[(Math.floor(i/project.value!.width)-minY)*w+(i%project.value!.width-minX)]=project.value!.cells[i]);return{width:w,height:h,cells}}
function pastePattern(pattern:{width:number;height:number;cells:Array<string|null>},index:number,base=[...project.value!.cells]){const sx=index%project.value!.width,sy=Math.floor(index/project.value!.width);pattern.cells.forEach((v,i)=>{if(!v)return;const x=sx+i%pattern.width,y=sy+Math.floor(i/pattern.width);if(x<project.value!.width&&y<project.value!.height)base[y*project.value!.width+x]=v});return base}
function canvasAction(index:number){if(!project.value)return
  if(tool.value==='copy'){const ids=connected(index);if(!ids.length)return showToast('请选择有拼豆的区域');clipboard.value=regionPattern(ids);tool.value='paste';showToast(`已复制 ${ids.length} 颗拼豆`)}
  else if(tool.value==='move'){if(!pendingMove.value){const ids=connected(index);if(!ids.length)return showToast('请选择要移动的连续区域');pendingMove.value={ids,...regionPattern(ids)};showToast('拖动高亮选区可连续调整位置')}else{const pattern=pendingMove.value,next=[...project.value.cells];pattern.ids.forEach(i=>next[i]=null);const placed=pastePattern(pattern,index,next);change(placed);const sx=index%project.value.width,sy=Math.floor(index/project.value.width),ids:number[]=[];pattern.cells.forEach((value,i)=>{if(!value)return;const x=sx+i%pattern.width,y=sy+Math.floor(i/pattern.width);if(x<project.value!.width&&y<project.value!.height)ids.push(y*project.value!.width+x)});pendingMove.value={...pattern,ids};showToast('选区已移动，可继续拖动') }}
  else if(tool.value==='paste'&&clipboard.value)change(pastePattern(clipboard.value,index))
  else if(tool.value==='text'){const text=window.prompt('输入要转换的文字','ABC');if(!text)return;const c=document.createElement('canvas');c.width=Math.max(24,text.length*18);c.height=22;const ctx=c.getContext('2d')!;ctx.fillStyle='#fff';ctx.font='bold 18px Noto Sans SC';ctx.textBaseline='top';ctx.fillText(text,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data,next=[...project.value.cells],sx=index%project.value.width,sy=Math.floor(index/project.value.width);for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(data[(y*c.width+x)*4+3]>80){const px=sx+x,py=sy+y;if(px<project.value.width&&py<project.value.height)next[py*project.value.width+px]=color.value}change(next)}
}
function rectangleIndices(start:number,end:number){const sx=start%project.value!.width,sy=Math.floor(start/project.value!.width),ex=end%project.value!.width,ey=Math.floor(end/project.value!.width),ids:number[]=[];for(let y=Math.min(sy,ey);y<=Math.max(sy,ey);y++)for(let x=Math.min(sx,ex);x<=Math.max(sx,ex);x++)ids.push(y*project.value!.width+x);return ids}
function rangeAction(rangeTool:Tool,start:number,end:number){if(!project.value)return;if(rangeTool==='move'&&pendingMove.value){const x=Math.max(0,Math.min(project.value.width-pendingMove.value.width,end%project.value.width-Math.floor(pendingMove.value.width/2))),y=Math.max(0,Math.min(project.value.height-pendingMove.value.height,Math.floor(end/project.value.width)-Math.floor(pendingMove.value.height/2)));canvasAction(y*project.value.width+x);return}const ids=rectangleIndices(start,end),next=[...project.value.cells];if(rangeTool==='fill'||rangeTool==='shape'){ids.forEach(index=>next[index]=color.value);change(next)}else if(rangeTool==='remove'){ids.forEach(index=>next[index]=null);change(next)}else if(rangeTool==='copy'){clipboard.value=regionPattern(ids);activateTool('paste');showToast(`已复制 ${ids.length} 格选区`)}else if(rangeTool==='move'){pendingMove.value={ids,...regionPattern(ids)};showToast('选区已浮起，拖动后点击完成放下')}}
async function clearAll(){if(!project.value?.cells.some(Boolean))return;try{await showConfirmDialog({title:'清空拼豆层？',message:'当前画布中的所有拼豆都会被移除，可使用撤销恢复。'});change(Array(project.value.cells.length).fill(null))}catch{}}
function resizeCells(cells:Array<string|null>,oldW:number,oldH:number,newW:number,newH:number,anchorX:-1|0|1=-1,anchorY:-1|0|1=-1){const next=Array<string|null>(newW*newH).fill(null),dx=anchorX===-1?0:anchorX===0?Math.floor((newW-oldW)/2):newW-oldW,dy=anchorY===-1?0:anchorY===0?Math.floor((newH-oldH)/2):newH-oldH;for(let y=0;y<oldH;y++)for(let x=0;x<oldW;x++){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<newW&&ny<newH)next[ny*newW+nx]=cells[y*oldW+x]}return next}
function clampSize(value:number){return Math.max(8,Math.min(180,Math.round(value||8)))}
function syncWidth(event:Event){const value=Number((event.target as HTMLInputElement).value);if(ratioLocked.value&&project.value&&value>0)heightDraft.value=clampSize(value*project.value.height/project.value.width);selectedPreset.value=''}
function syncHeight(event:Event){const value=Number((event.target as HTMLInputElement).value);if(ratioLocked.value&&project.value&&value>0)widthDraft.value=clampSize(value*project.value.width/project.value.height);selectedPreset.value=''}
function changeWidth(){widthDraft.value=clampSize(widthDraft.value);if(ratioLocked.value&&project.value)heightDraft.value=clampSize(widthDraft.value*project.value.height/project.value.width);selectedPreset.value=''}
function changeHeight(){heightDraft.value=clampSize(heightDraft.value);if(ratioLocked.value&&project.value)widthDraft.value=clampSize(heightDraft.value*project.value.width/project.value.height);selectedPreset.value=''}
function resize(){if(!project.value||!rawProject.value)return;widthDraft.value=clampSize(widthDraft.value);heightDraft.value=clampSize(heightDraft.value);if(widthDraft.value===project.value.width&&heightDraft.value===project.value.height)return;resizeOffsetX.value=Math.floor((widthDraft.value-project.value.width)/2);resizeOffsetY.value=Math.floor((heightDraft.value-project.value.height)/2);resizeOpen.value=true}
function resizeCellsAt(cells:Array<string|null>,oldW:number,oldH:number,newW:number,newH:number,dx:number,dy:number){const next=Array<string|null>(newW*newH).fill(null);for(let y=0;y<oldH;y++)for(let x=0;x<oldW;x++){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<newW&&ny<newH)next[ny*newW+nx]=cells[y*oldW+x]}return next}
function applyResize(){if(!project.value||!rawProject.value)return;const w=widthDraft.value,h=heightDraft.value;pushHistory(snapshot());future.value=[];const next=layers.value.map(layer=>({...layer,cells:resizeCellsAt(layer.cells,project.value!.width,project.value!.height,w,h,resizeOffsetX.value,resizeOffsetY.value)}));saveLayers(next,rawProject.value.activeLayerId,w,h);selectedPreset.value=[52,78,104,156].includes(w)&&w===h?`${w}x${h}`:'';resizeOpen.value=false;showToast('已按预览位置调整画布')}
function resizeDragStart(event:PointerEvent){resizeDragging=true;resizePointerX=event.clientX;resizePointerY=event.clientY;(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId)}
function resizeDragMove(event:PointerEvent){if(!resizeDragging||!project.value)return;const rect=(event.currentTarget as HTMLElement).getBoundingClientRect(),dx=Math.round((event.clientX-resizePointerX)/rect.width*widthDraft.value),dy=Math.round((event.clientY-resizePointerY)/rect.height*heightDraft.value),minX=Math.min(0,widthDraft.value-project.value.width),maxX=Math.max(0,widthDraft.value-project.value.width),minY=Math.min(0,heightDraft.value-project.value.height),maxY=Math.max(0,heightDraft.value-project.value.height);resizeOffsetX.value=Math.max(minX,Math.min(maxX,resizeOffsetX.value+dx));resizeOffsetY.value=Math.max(minY,Math.min(maxY,resizeOffsetY.value+dy));resizePointerX=event.clientX;resizePointerY=event.clientY}
function resizeDragStop(){resizeDragging=false}
function setOpacity(layer:ProjectLayer,event:Event){const value=Number((event.target as HTMLInputElement).value);opacityBubble.value=Math.round(value*100);patchLayer(layer.id,{opacity:value})}
function choosePreset(){if(!selectedPreset.value)return;const [w,h]=selectedPreset.value.split('x').map(Number);widthDraft.value=w;heightDraft.value=h}
function zoomAtPointer(event:WheelEvent){const area=event.currentTarget as HTMLElement,old=zoom.value,step=event.deltaY<0?1.2:1/1.2,next=Math.max(.35,Math.min(6,Math.round(old*step*100)/100));if(next===old)return;const rect=area.getBoundingClientRect(),x=event.clientX-rect.left+area.scrollLeft,y=event.clientY-rect.top+area.scrollTop,ratio=next/old;zoom.value=next;showToast(`画布缩放 ${Math.round(next*100)}%`);requestAnimationFrame(()=>{area.scrollLeft=x*ratio-(event.clientX-rect.left);area.scrollTop=y*ratio-(event.clientY-rect.top)})}
function mirror(horizontal=true){if(!project.value)return;const {width:w,height:h,cells}=project.value,next=Array<string|null>(cells.length).fill(null);for(let y=0;y<h;y++)for(let x=0;x<w;x++)next[(horizontal?y:h-1-y)*w+(horizontal?w-1-x:x)]=cells[y*w+x];change(next)}
function exportJson(){if(project.value)download(new Blob([JSON.stringify(project.value,null,2)],{type:'application/json'}),`${project.value.name}.json`)}
function exportPng(){
  if(!project.value)return
  const current=project.value,cells=visibleCells.value
  const used=palette.map(item=>({item,count:cells.filter(code=>code===item.code).length})).filter(row=>row.count).sort((a,b)=>a.item.code.localeCompare(b.item.code,undefined,{numeric:true}))
  const cell=30,padding=36,titleHeight=64,legendCols=8,legendCellW=132,legendRows=Math.ceil(used.length/legendCols),legendHeight=used.length?legendRows*42+42:42
  const width=Math.max(current.width*cell+padding*2,legendCols*legendCellW+padding*2),height=titleHeight+current.height*cell+legendHeight+padding*2,canvas=document.createElement('canvas'),dpr=2
  canvas.width=width*dpr;canvas.height=height*dpr
  const ctx=canvas.getContext('2d')!;ctx.scale(dpr,dpr);ctx.fillStyle='#fffdf7';ctx.fillRect(0,0,width,height);ctx.fillStyle='#574437';ctx.font='800 24px "Noto Sans SC"';ctx.textAlign='left';ctx.fillText(current.name,padding,38);ctx.font='600 13px "Noto Sans SC"';ctx.textAlign='right';ctx.fillText(`${current.width} × ${current.height} · ${used.length} 色`,width-padding,36)
  const ox=(width-current.width*cell)/2,oy=titleHeight
  cells.forEach((code,index)=>{const x=ox+(index%current.width)*cell,y=oy+Math.floor(index/current.width)*cell;ctx.fillStyle=code?(colorByCode(code)?.hex??'#fff'):'#fff';ctx.fillRect(x,y,cell,cell);if(code){const rgb=rgbOf(colorByCode(code)?.hex??'#fff'),lum=rgb[0]*.299+rgb[1]*.587+rgb[2]*.114;ctx.fillStyle=lum<145?'#fff':'#574437';ctx.font='700 8px Nunito';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(code,x+cell/2,y+cell/2)}})
  for(let x=0;x<=current.width;x++){const major=x%10===0,medium=x%5===0;ctx.beginPath();ctx.strokeStyle=major?'rgba(87,68,55,.82)':medium?'rgba(87,68,55,.58)':'rgba(87,68,55,.25)';ctx.lineWidth=major?2.5:medium?1.5:.6;ctx.moveTo(ox+x*cell,oy);ctx.lineTo(ox+x*cell,oy+current.height*cell);ctx.stroke()}
  for(let y=0;y<=current.height;y++){const major=y%10===0,medium=y%5===0;ctx.beginPath();ctx.strokeStyle=major?'rgba(87,68,55,.82)':medium?'rgba(87,68,55,.58)':'rgba(87,68,55,.25)';ctx.lineWidth=major?2.5:medium?1.5:.6;ctx.moveTo(ox,oy+y*cell);ctx.lineTo(ox+current.width*cell,oy+y*cell);ctx.stroke()}
  const ly=oy+current.height*cell+28;ctx.textBaseline='alphabetic';ctx.textAlign='left';ctx.fillStyle='#574437';ctx.font='800 14px "Noto Sans SC"';ctx.fillText('拼豆用量',padding,ly)
  used.forEach((row,index)=>{const col=index%legendCols,r=Math.floor(index/legendCols),x=padding+col*legendCellW,y=ly+16+r*42;ctx.fillStyle=row.item.hex;ctx.fillRect(x,y,28,28);ctx.strokeStyle='rgba(87,68,55,.35)';ctx.strokeRect(x+.5,y+.5,27,27);const rgb=rgbOf(row.item.hex),lum=rgb[0]*.299+rgb[1]*.587+rgb[2]*.114;ctx.fillStyle=lum<145?'#fff':'#574437';ctx.font='700 8px Nunito';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(row.item.code,x+14,y+14);ctx.fillStyle='#574437';ctx.font='700 12px Nunito';ctx.textAlign='left';ctx.fillText(`× ${row.count}`,x+36,y+15)})
  canvas.toBlob(blob=>blob&&download(blob,`${current.name}-图纸.png`))
}
function download(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function selectImage(){fileInput.value?.click()}
function resetCrop(){cropZoom.value=1;cropX.value=0;cropY.value=0}
function cropStart(e:PointerEvent){cropDragging=true;cropPointerX=e.clientX;cropPointerY=e.clientY;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}
function cropMove(e:PointerEvent){if(!cropDragging)return;const rect=(e.currentTarget as HTMLElement).getBoundingClientRect();cropX.value=Math.max(-1,Math.min(1,cropX.value+(e.clientX-cropPointerX)/rect.width*2*cropZoom.value));cropY.value=Math.max(-1,Math.min(1,cropY.value+(e.clientY-cropPointerY)/rect.height*2*cropZoom.value));cropPointerX=e.clientX;cropPointerY=e.clientY}
function cropStop(){cropDragging=false}
function loadFile(e:Event){const input=e.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(pendingImageUrl.value)URL.revokeObjectURL(pendingImageUrl.value);pendingImageUrl.value=URL.createObjectURL(file);pendingImageName.value=file.name.replace(/\.[^.]+$/,'')||'导入图片';generatedLayerName.value=pendingImageName.value;convertWidth.value=Math.min(180,project.value?.width??52);importDraft.value=null;resetCrop();importMenuOpen.value=true;input.value=''}
function saveImportedCrop(){if(!importDraft.value||!project.value||!rawProject.value)return;const draft=importDraft.value,cw=Math.max(1,Math.round(draft.width/cropZoom.value)),ch=Math.max(1,Math.round(draft.height/cropZoom.value)),sx=Math.round((draft.width-cw)*(cropX.value+1)/2),sy=Math.round((draft.height-ch)*(cropY.value+1)/2),cropped=Array<string|null>(cw*ch).fill(null);for(let y=0;y<ch;y++)for(let x=0;x<cw;x++)cropped[y*cw+x]=draft.cells[(sy+y)*draft.width+sx+x];const canvasWidth=Math.max(project.value.width,cw),canvasHeight=Math.max(project.value.height,ch),cells=Array<string|null>(canvasWidth*canvasHeight).fill(null);cropped.forEach((cell,index)=>cells[Math.floor(index/cw)*canvasWidth+index%cw]=cell);const resized=layers.value.map(layer=>({...layer,cells:resizeCells(layer.cells,project.value!.width,project.value!.height,canvasWidth,canvasHeight)})),used=new Set(cropped.filter(Boolean)).size,layer:ProjectLayer={id:crypto.randomUUID(),name:`${used} 色-${generatedLayerName.value.trim()||pendingImageName.value||'导入图纸'}`,type:'bead',visible:true,locked:false,opacity:1,cells};saveLayers([...resized,layer],layer.id,canvasWidth,canvasHeight);widthDraft.value=canvasWidth;heightDraft.value=canvasHeight;importDraft.value=null;importMenuOpen.value=false;showToast(`已按拼豆预览剪裁并生成 ${used} 色图层`)}
function rgbOf(hex:string){const value=parseInt(hex.slice(1),16);return[value>>16,(value>>8)&255,value&255]}
function readableColor(hex:string){const [r,g,b]=rgbOf(hex);return r*.299+g*.587+b*.114<150?'#fff':'#302b28'}
function distance(a:number[],b:number[]){return(a[0]-b[0])**2+(a[1]-b[1])**2+(a[2]-b[2])**2}
function generateImportedLayer(){
  if(importDraft.value)return saveImportedCrop()
  const url=pendingImageUrl.value;if(!url)return
  const image=new Image();image.onload=()=>{
    const w=Math.max(8,Math.min(180,Math.round(convertWidth.value))),h=Math.max(8,Math.min(180,Math.round(w*image.height/image.width))),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h
    const ctx=canvas.getContext('2d')!;ctx.imageSmoothingEnabled=generationStyle.value==='realistic';ctx.drawImage(image,0,0,w,h)
    const data=ctx.getImageData(0,0,w,h).data,sourceRgb:Array<number[]|null>=[],counts=new Map<string,number>(),corners=[[0,0],[w-1,0],[0,h-1],[w-1,h-1]],background=[0,1,2].map(channel=>Math.round(corners.reduce((sum,[x,y])=>sum+data[(y*w+x)*4+channel],0)/4))
    for(let i=0;i<w*h;i++){if(data[i*4+3]<40){sourceRgb.push(null);continue}let rgb=[data[i*4],data[i*4+1],data[i*4+2]];if(backgroundMode.value==='remove'&&Math.sqrt(distance(rgb,background))<=backgroundTolerance.value){sourceRgb.push(null);continue}if(generationStyle.value==='cartoon')rgb=rgb.map(value=>Math.round(value/20)*20);sourceRgb.push(rgb);let best=palette[0],bestDistance=Infinity;for(const item of palette){const value=distance(rgb,rgbOf(item.hex));if(value<bestDistance){bestDistance=value;best=item}}counts.set(best.code,(counts.get(best.code)??0)+1)}
    const candidateCodes=[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,Math.max(2,Math.min(48,maxColors.value))).map(([code])=>code),candidates=palette.filter(item=>candidateCodes.includes(item.code)),generated=sourceRgb.map(rgb=>{if(!rgb)return null;let best=candidates[0]??palette[0],bestDistance=Infinity;for(const item of candidates){const value=distance(rgb,rgbOf(item.hex));if(value<bestDistance){bestDistance=value;best=item}}return best.code}),used=new Set(generated.filter(Boolean)).size
    importDraft.value={width:w,height:h,cells:generated,colors:used};resetCrop();importMenuOpen.value=false;showToast('拼豆预览已放入拼豆板，请框选保留区域')
  };image.src=url
}
function cancelImportedCrop(){importDraft.value=null;resetCrop();showToast('已取消导入剪裁')}
function addBeadLayer(){if(!rawProject.value)return;const layer:ProjectLayer={id:crypto.randomUUID(),name:`拼豆层 ${layers.value.filter(item=>item.type==='bead').length+1}`,type:'bead',visible:true,locked:false,opacity:1,cells:Array(rawProject.value.width*rawProject.value.height).fill(null)};saveLayers([...layers.value,layer],layer.id);newLayerMenu.value=false}
function chooseReferenceLayer(){referenceInput.value?.click();newLayerMenu.value=false}
function addReferenceLayer(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file||!rawProject.value)return;const layer:ProjectLayer={id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,''),type:'reference',visible:true,locked:false,opacity:.35,cells:Array(rawProject.value.width*rawProject.value.height).fill(null),imageUrl:URL.createObjectURL(file)};saveLayers([...layers.value,layer],layer.id);(event.target as HTMLInputElement).value=''}
function patchLayer(id:string,patch:Partial<ProjectLayer>){saveLayers(layers.value.map(layer=>layer.id===id?{...layer,...patch}:layer),rawProject.value!.activeLayerId)}
async function deleteLayer(layer:ProjectLayer){if(layers.value.length===1)return showToast('至少保留一个图层');try{await showConfirmDialog({title:`删除「${layer.name}」？`,message:'图层内容删除后无法恢复。',confirmButtonText:'确认删除'});const next=layers.value.filter(item=>item.id!==layer.id);const active=rawProject.value!.activeLayerId===layer.id?(next.find(item=>item.type==='bead')?.id??next[0].id):rawProject.value!.activeLayerId;saveLayers(next,active)}catch{}layerMenuId.value=null}
function closeTransient(){openToolGroup.value=null;importMenuOpen.value=false;paletteExpanded.value=false;tool.value='pan';pendingMove.value=null}
function selectLayer(layer:ProjectLayer){closeTransient();saveLayers(layers.value,layer.id);layerMenuId.value=null}
function toggleLayerMenu(layer:ProjectLayer){
  const shouldOpen=layerMenuId.value!==layer.id
  saveLayers(layers.value,layer.id)
  layerMenuId.value=shouldOpen?layer.id:null
}
function dropLayer(targetId:string){if(!draggedLayerId.value||draggedLayerId.value===targetId)return;const next=[...layers.value],from=next.findIndex(layer=>layer.id===draggedLayerId.value),to=next.findIndex(layer=>layer.id===targetId),[moved]=next.splice(from,1);next.splice(to,0,moved);saveLayers(next);draggedLayerId.value=null}
onMounted(()=>{document.body.classList.add('studio-locked');document.addEventListener('pointerdown',handleOutside);if(!project.value)return router.replace('/');widthDraft.value=project.value.width;heightDraft.value=project.value.height;selectedPreset.value=[52,78,104,156].includes(project.value.width)&&project.value.width===project.value.height?`${project.value.width}x${project.value.height}`:'';const url=sessionStorage.getItem(`pocket-pin:import:${project.value.id}`);if(url){sessionStorage.removeItem(`pocket-pin:import:${project.value.id}`);pendingImageUrl.value=url;pendingImageName.value=project.value.name;generatedLayerName.value=project.value.name;convertWidth.value=project.value.width;importMenuOpen.value=true}})
onUnmounted(()=>{document.body.classList.remove('studio-locked');document.removeEventListener('pointerdown',handleOutside)})
</script>

<template><app-shell v-if="project" :title="project.name" back @back="router.push('/')" @title-click="renameCurrent">
  <template #center><div class="board-size title-board-size"><b>拼豆板</b><input v-model.number="widthDraft" aria-label="画布宽度" type="number" min="8" max="180" @input="syncWidth" @change="changeWidth"><button class="ratio-lock" :class="{active:ratioLocked}" :aria-label="ratioLocked?'解除宽高比锁定':'锁定宽高比'" :title="ratioLocked?'已锁定原始宽高比':'宽高可独立修改'" @click="ratioLocked=!ratioLocked"><lock-glyph :locked="ratioLocked"/></button><input v-model.number="heightDraft" aria-label="画布高度" type="number" min="8" max="180" @input="syncHeight" @change="changeHeight"><label class="size-select"><select v-model="selectedPreset" aria-label="常用画布尺寸" @change="choosePreset"><option value="">常用尺寸</option><option value="52x52">52 × 52</option><option value="78x78">78 × 78</option><option value="104x104">104 × 104</option><option value="156x156">156 × 156</option></select><van-icon name="arrow-down"/></label><button title="应用新的画布尺寸" @click="resize">应用</button></div></template>
  <template #actions><div class="header-actions"><button class="danger-action" title="清空当前拼豆层" @click="clearAll"><van-icon name="delete-o"/><span>清空</span></button><button :disabled="!history.length" :data-history-count="history.length" title="撤销上一步编辑" @click="undo"><van-icon name="revoke"/><span>撤销</span></button><button :disabled="!future.length" title="重做已撤销的编辑" @click="redo"><van-icon name="replay"/><span>重做</span></button><button class="primary" title="导出当前 PNG 图纸" @click="exportPng"><van-icon name="down"/><span>导出图纸</span></button><button class="icon-button mobile-panel-button" title="打开图层" @click="layersOpen=!layersOpen"><van-icon name="cluster-o"/></button><button class="icon-button mobile-panel-button" title="打开右侧面板" @click="panelOpen=!panelOpen"><van-icon name="setting-o"/></button></div></template>
  <div class="editor-toolbar">
    <div class="tool-groups">
      <button class="tool-group-trigger" :class="{active:tool==='pan'}" title="拖动或滚动查看大画布" @click="activateTool('pan')"><tool-glyph name="pan"/><span>拖动</span></button>
      <div class="tool-group"><button class="tool-group-trigger" :class="{active:drawToolIds.includes(tool)}" title="绘制、形状和填色工具" @click="toggleToolGroup('draw')"><tool-glyph name="pencil"/><span>编辑</span><van-icon name="arrow-down"/></button><div v-if="openToolGroup==='draw'" class="tool-popover"><button v-for="item in tools.filter(item=>drawToolIds.includes(item.id))" :key="item.id" :class="{active:tool===item.id}" :title="`${item.label}：${toolHint(item.id)}`" @click="activateTool(item.id)"><tool-glyph :name="item.id"/><span>{{item.label}}</span></button></div></div>
      <div class="tool-group"><button class="tool-group-trigger" :class="{active:selectToolIds.includes(tool)}" title="矩形选区工具" @click="toggleToolGroup('select')"><tool-glyph name="move"/><span>选区</span><van-icon name="arrow-down"/></button><div v-if="openToolGroup==='select'" class="tool-popover"><button v-for="item in tools.filter(item=>selectToolIds.includes(item.id))" :key="item.id" :class="{active:tool===item.id}" :title="item.id==='paste'?'点击位置放下已复制内容':'沿对角线拖出矩形选区'" @click="activateTool(item.id)"><tool-glyph :name="item.id"/><span>{{item.label}}</span></button></div></div>
      <div class="tool-group import-tool-group"><button class="tool-group-trigger" :class="{active:importMenuOpen}" title="从设备选择图片并配置生成图纸" @click="pendingImageUrl?importMenuOpen=!importMenuOpen:selectImage()"><tool-glyph name="import"/><span>导入</span><van-icon name="arrow-down"/></button><input ref="fileInput" class="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" @change="loadFile"><div v-if="importMenuOpen" class="import-config-popover"><div class="import-preview" @click="selectImage"><img v-if="pendingImageUrl" :src="pendingImageUrl" alt="导入原图完整预览"><span><b>{{pendingImageName||'选择图片'}}</b><small>完整原图预览 · 点击更换</small></span></div><div class="import-config-grid"><label><span>目标宽度</span><input v-model.number="convertWidth" type="number" min="8" max="180"></label><label class="range-field"><span>色数上限 <b>{{maxColors}}</b></span><input v-model.number="maxColors" type="range" min="2" max="48" step="1"></label><label><span>生成风格</span><select v-model="generationStyle"><option value="cartoon">卡通</option><option value="realistic">写实</option></select></label><label><span>背景方式</span><select v-model="backgroundMode"><option value="keep">保留背景</option><option value="remove">移除背景</option></select></label><label v-if="backgroundMode==='remove'" class="range-field full"><span>去背景容差 <b>{{backgroundTolerance}}</b></span><input v-model.number="backgroundTolerance" type="range" min="0" max="120"></label><label class="full"><span>图层名称</span><input v-model="generatedLayerName" maxlength="36" placeholder="例如：头像"></label></div><button class="generate-layer-button" :disabled="!pendingImageUrl" @click="generateImportedLayer">生成完整拼豆预览</button></div></div>
    </div>
    <div class="toolbar-balance"></div>
  </div>
  <div v-if="tool==='recolor'" class="recolor-mode-bar"><span>换色范围</span><button :class="{active:recolorMode==='single'}" @click="recolorMode='single'">单个拼豆</button><button :class="{active:recolorMode==='same'}" @click="recolorMode='same'">相同色号批量</button></div>
  <main class="studio-page figma-studio">
    <aside :class="['layers-sidebar',{open:layersOpen}]">
      <div class="layers-header"><div><b>图层</b><span>{{layers.length}}</span></div><button aria-label="新建图层" @click="newLayerMenu=!newLayerMenu"><van-icon name="plus"/></button><div v-if="newLayerMenu" class="new-layer-menu"><button @click="addBeadLayer"><van-icon name="apps-o"/><span><b>拼豆层</b><small>可绘制与统计用量</small></span></button><button @click="chooseReferenceLayer"><van-icon name="photo-o"/><span><b>照片参考层</b><small>仅作为辅助底图</small></span></button></div><input ref="referenceInput" class="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" @change="addReferenceLayer"></div>
      <button class="workspace-preview" title="打开完整图纸预览" @click="previewOpen=true"><mini-preview :width="project.width" :height="project.height" :cells="visibleCells"/></button>
      <div class="layers-list"><article v-for="layer in [...layers].reverse()" :key="layer.id" draggable="true" :class="['figma-layer',{active:layer.id===rawProject?.activeLayerId,hidden:!layer.visible}]" @click="selectLayer(layer)" @dragstart="draggedLayerId=layer.id" @dragover.prevent @drop="dropLayer(layer.id)"><div class="layer-thumb"><van-icon :name="layer.type==='bead'?'apps-o':'photo-o'"/></div><div class="layer-name"><b>{{layer.name}}</b><small>{{layer.type==='bead'?`${layer.cells.filter(Boolean).length} 颗拼豆`:'照片参考'}}</small></div><button :aria-label="layer.visible?'隐藏图层':'显示图层'" @click.stop="patchLayer(layer.id,{visible:!layer.visible})"><van-icon :name="layer.visible?'eye-o':'closed-eye'"/></button><button :class="['layer-lock',{locked:layer.locked}]" :aria-label="layer.locked?'解锁图层':'锁定图层'" @click.stop="patchLayer(layer.id,{locked:!layer.locked})"><lock-glyph :locked="layer.locked"/></button><button class="layer-delete" aria-label="删除图层" @click.stop="deleteLayer(layer)"><van-icon name="delete-o"/></button></article></div>
    </aside>
    <section class="canvas-area"><div class="canvas-info"><b>{{importDraft?`${importDraft.width} × ${importDraft.height}`:`${project.width} × ${project.height}`}}</b><span v-if="importDraft">剪裁拼豆预览</span><template v-else><span>{{visibleCells.filter(Boolean).length}} 颗</span><span>网格 {{project.width * project.height}} 格</span><span>自动保存</span></template></div><div v-if="importDraft" class="canvas-scroll import-board-crop"><div class="board-crop-stage" :style="{aspectRatio:`${importDraft.width} / ${importDraft.height}`}" @pointerdown="cropStart" @pointermove="cropMove" @pointerup="cropStop" @pointercancel="cropStop"><mini-preview detailed :width="importDraft.width" :height="importDraft.height" :cells="importDraft.cells"/><div class="crop-selection" :style="{width:`${100/cropZoom}%`,height:`${100/cropZoom}%`,left:`${(100-100/cropZoom)*(cropX+1)/2}%`,top:`${(100-100/cropZoom)*(cropY+1)/2}%`}"><div class="crop-grid"></div><i class="crop-corner tl"></i><i class="crop-corner tr"></i><i class="crop-corner bl"></i><i class="crop-corner br"></i></div></div><div class="board-crop-actions"><button @click="cancelImportedCrop">取消</button><label>剪裁范围 <b>{{Math.round(100/cropZoom)}}%</b><input v-model.number="cropZoom" type="range" min="1" max="3" step=".05"></label><button class="primary" @click="saveImportedCrop">按选区创建图层</button></div></div><div v-else class="canvas-scroll" @wheel.prevent="zoomAtPointer"><div class="canvas-scale layer-canvas-stack"><img v-for="layer in layers.filter(item=>item.type==='reference'&&item.visible&&item.imageUrl)" :key="layer.id" class="reference-layer-image" :src="layer.imageUrl" :style="{opacity:layer.opacity}"><bead-canvas :project="project" :layers="layers" :tool="tool" :color="color" :grid="grid" :coordinates="coordinates" :round="round" :zoom="zoom" :board-tone="boardTone" :recolor-mode="recolorMode" :move-pending="Boolean(pendingMove)" :selected-ids="pendingMove?.ids??[]" :locked="activeLayer?.locked||activeLayer?.type!=='bead'" @change="change" @pick="pick" @focus="focusBead" @action="canvasAction" @range="rangeAction"/></div></div></section>
    <aside class="studio-panel pro-panel" :class="{open:panelOpen}"><div class="panel-tabs two"><button :class="{active:panel==='adjust'}" @click="panel='adjust'">属性</button><button :class="{active:panel==='usage'}" @click="panel='usage'">用量</button></div><template v-if="panel==='usage'"><div class="usage-total"><strong>{{visibleCells.filter(Boolean).length}}</strong><span>总颗数 · {{usage.length}} 种颜色</span></div><div class="usage-compact"><div v-for="row in usage" :key="row.color.code"><i :style="{background:row.color.hex,color:readableColor(row.color.hex)}"><b>{{row.color.code}}</b></i><span>× {{row.count}}</span></div></div></template><template v-else><div class="property-list"><div><span><b><van-icon name="apps-o"/>定位网格</b><small>缩小后自动弱化或隐藏</small></span><div class="segmented-toggle"><button :class="{active:!grid}" @click="grid=false">关闭</button><button :class="{active:grid}" @click="grid=true">开启</button></div></div><div><span><b><van-icon name="label-o"/>显示坐标</b><small>在豆板边缘标注编号</small></span><div class="segmented-toggle"><button :class="{active:!coordinates}" @click="coordinates=false">关闭</button><button :class="{active:coordinates}" @click="coordinates=true">开启</button></div></div><div><span><b><van-icon name="gem-o"/>预览形状</b><small>切换工作区拼豆外观</small></span><div class="segmented-toggle"><button :class="{active:!round}" @click="round=false">方豆</button><button :class="{active:round}" @click="round=true">圆豆</button></div></div><div><span><b><van-icon name="brush-o"/>豆板底色</b><small>切换浅色或深色豆板</small></span><div class="segmented-toggle"><button :class="{active:boardTone==='light'}" @click="boardTone='light'">白色</button><button :class="{active:boardTone==='dark'}" @click="boardTone='dark'">黑色</button></div></div><template v-if="activeLayer"><div><span><b><van-icon name="eye-o"/>图层透明度</b><small>拖动时查看数值</small></span><label class="opacity-control"><output v-if="opacityBubble!==null">{{opacityBubble}}%</output><input :value="activeLayer.opacity" type="range" min="0" max="1" step=".01" @input="setOpacity(activeLayer,$event)" @change="opacityBubble=null"></label></div><div v-if="activeLayer.type==='bead'" class="mirror-row"><span><b><van-icon name="exchange"/>镜像</b><small>翻转当前拼豆图层</small></span><div><button title="左右镜像" @click="mirror(true)"><van-icon name="exchange"/>左右</button><button title="上下镜像" @click="mirror(false)"><van-icon name="exchange" class="vertical-icon"/>上下</button></div></div></template></div></template></aside>
    <div v-if="activeLayer?.type==='bead'&&!activeLayer.locked&&['pencil','fill','recolor','text','eyedropper'].includes(tool)" :class="['bottom-palette',{expanded:paletteExpanded,recommending:tool==='recolor'&&recommendedColors.length}]"><div v-if="tool==='recolor'&&recommendedColors.length" class="recommended-swatches"><span>推荐相近色</span><button v-for="item in recommendedColors" :key="item.code" :title="`${item.code} ${item.name}`" @click="chooseRecommended(item.code)"><i :style="{background:item.hex}"></i><b>{{item.code}}</b></button></div><button class="palette-eyedropper" :class="{active:tool==='eyedropper'}" title="从画布吸取单个拼豆颜色，完成后返回当前工具" @click="activateTool('eyedropper')"><tool-glyph name="eyedropper"/></button><div class="palette-divider"></div><div class="palette-head"><button class="current-swatch" @click="paletteExpanded=!paletteExpanded"><i :style="{background:colorByCode(color)?.hex}"></i><b>{{color}}</b><span class="fold-icon"><van-icon :name="paletteExpanded?'arrow-down':'arrow-up'"/></span></button><div v-if="paletteExpanded" class="palette-groups"><button v-for="group in groups" :key="group" :class="{active:paletteGroup===group}" @click="paletteGroup=group">{{group}}</button></div></div><div class="quick-swatches"><button v-for="item in (paletteExpanded?filteredPalette:filteredPalette.slice(0,12))" :key="item.code" :aria-label="`${item.code} ${item.name}`" :class="{active:item.code===color}" @click="color=item.code"><i :style="{background:item.hex}"></i><span>{{item.code}}</span></button></div></div>
    <div v-if="pendingMove" class="move-confirm"><span><van-icon name="upgrade"/>选区已浮起</span><button @click="pendingMove=null">完成移动</button></div>
    <van-popup v-model:show="resizeOpen" teleport="body" class="resize-dialog"><button class="preview-close" aria-label="关闭" @click="resizeOpen=false"><van-icon name="cross"/></button><h3>调整拼豆板</h3><p>{{project.width}} × {{project.height}} → <b>{{widthDraft}} × {{heightDraft}}</b></p><div class="resize-stage-wrap"><div class="resize-preview" :style="{aspectRatio:`${widthDraft} / ${heightDraft}`,width:`${widthDraft>=heightDraft?280:280*widthDraft/heightDraft}px`}" @pointerdown="resizeDragStart" @pointermove="resizeDragMove" @pointerup="resizeDragStop" @pointercancel="resizeDragStop"><div class="resize-content" :style="{width:`${project.width/widthDraft*100}%`,height:`${project.height/heightDraft*100}%`,left:`${resizeOffsetX/widthDraft*100}%`,top:`${resizeOffsetY/heightDraft*100}%`}"><mini-preview :width="project.width" :height="project.height" :cells="visibleCells"/></div></div></div><span class="resize-hint"><van-icon name="upgrade"/>拖动已有内容，调整它在新画板中的位置</span><div class="resize-actions"><button @click="resizeOpen=false">取消</button><button class="primary" @click="applyResize">应用并裁剪</button></div></van-popup>
    <van-popup v-model:show="previewOpen" teleport="body" class="preview-dialog"><button class="preview-close" aria-label="关闭预览" @click="previewOpen=false"><van-icon name="cross"/></button><h3>{{project.name}}</h3><div><mini-preview detailed :width="project.width" :height="project.height" :cells="visibleCells"/></div><p>{{project.width}} × {{project.height}} · {{usage.length}} 色 · {{visibleCells.filter(Boolean).length}} 颗</p></van-popup>
    <van-popup v-model:show="layerSheetOpen" position="bottom" round teleport="body" :lock-scroll="false" class="more-sheet"><div v-if="menuLayer" class="sheet-content"><div class="sheet-handle"></div><h3>{{menuLayer.name}}</h3><label class="sheet-opacity">不透明度<input :value="menuLayer.opacity" type="range" min="0" max="1" step=".01" @input="setOpacity(menuLayer,$event)" @change="opacityBubble=null"></label><div v-if="menuLayer.type==='bead'" class="sheet-actions mirror-sheet-actions"><button @click="mirror(true);layerSheetOpen=false"><van-icon name="exchange"/>左右镜像</button><button @click="mirror(false);layerSheetOpen=false"><van-icon name="exchange" class="vertical-icon"/>上下镜像</button></div><button class="sheet-danger" @click="deleteLayer(menuLayer)"><van-icon name="delete-o"/>删除图层</button></div></van-popup>
  </main></app-shell></template>
