import { mount } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'
import { createRouter, createMemoryHistory } from 'vue-router'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { useProjectStore } from '@/modules/projects/projectStore'
import StudioPage from './StudioPage.vue'
vi.mock('vant',async()=>({...await vi.importActual('vant'),showConfirmDialog:vi.fn(()=>Promise.resolve())}))
beforeEach(()=>localStorage.clear())
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();vi.useRealTimers()})
async function setup(){const pinia=createPinia();setActivePinia(pinia);const store=useProjectStore(),p=store.create();const cells=[...p.cells];cells[0]='H7';cells[1]='H7';cells[3]='H2';store.update({...p,cells,layers:[{...p.layers[0],cells}]});const router=createRouter({history:createMemoryHistory(),routes:[{path:'/studio/:id',component:StudioPage}]});await router.push(`/studio/${p.id}`);const w=mount(StudioPage,{global:{plugins:[pinia,router],stubs:{BeadCanvas:{name:'BeadCanvas',props:['tool','color','width','height','cells'],template:'<div/>',methods:{cancel:vi.fn(),fit:vi.fn(),endPreview:vi.fn()}}}}});return {w,store}}
async function button(w:Awaited<ReturnType<typeof setup>>['w'],text:string){const b=w.findAll('button').find(b=>b.attributes('aria-label')===text||b.text()===text||b.text().includes(text));expect(b, text).toBeTruthy();await b!.trigger('click')}
describe('focused editor sessions',()=>{
 it('holds brush changes until confirmation and discards on cancel',async()=>{const {w,store}=await setup();await button(w,'画笔');const c=[...store.current!.cells];c[4]='A1';w.findComponent({name:'BeadCanvas'}).vm.$emit('change',c);await w.vm.$nextTick();expect(store.current!.cells[4]).toBeNull();await button(w,'取消当前操作');expect(store.current!.cells[4]).toBeNull();await button(w,'画笔');w.findComponent({name:'BeadCanvas'}).vm.$emit('change',c);await w.vm.$nextTick();await button(w,'保存当前操作');expect(store.current!.cells[4]).toBe('A1');w.unmount()})
 it('undoes individual strokes inside a session and the entire saved session outside',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'画笔');expect(w.find('.pin-peek').exists()).toBe(false);const board=w.findComponent({name:'BeadCanvas'}),a=[...original];a[4]='A1';board.vm.$emit('change',a);await w.vm.$nextTick();const b=[...a];b[5]='A2';board.vm.$emit('change',b);await w.vm.$nextTick();await button(w,'撤销');await button(w,'重做');expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');expect(store.current!.cells).toEqual(b);expect(w.find('.pin-peek').exists()).toBe(true);await button(w,'撤销');expect(store.current!.cells).toEqual(original);await button(w,'重做');expect(store.current!.cells).toEqual(b);await button(w,'画笔');expect(w.find('[aria-label="撤销"]').attributes('disabled')).toBeDefined();await button(w,'取消当前操作');w.unmount()})
 it('composes mirror clicks and commits the displayed result',async()=>{const {w,store}=await setup();await button(w,'编辑');await button(w,'水平镜像');await button(w,'垂直镜像');expect(store.current!.cells[0]).toBeNull();expect(store.current!.cells.at(-1)).toBe('H7');w.unmount()})
 it('mirrors directly and cycles grid and bead shape from the edit menu',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'编辑');await button(w,'水平镜像');await button(w,'水平镜像');expect(store.current!.cells).toEqual(original);expect(w.find('.pin-mode-dock').exists()).toBe(false);await button(w,'自动网格');expect(store.current!.settings?.grid).toBe('off');await button(w,'隐藏网格');expect(store.current!.settings?.grid).toBe('always');await button(w,'显示网格');expect(store.current!.settings?.grid).toBe('auto');await button(w,'方豆');expect(store.current!.settings?.round).toBe(true);expect(w.text()).not.toContain('减少用色');w.unmount()})

 it('enters selection before drawing and keeps selection edits in local history',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'选区');expect(w.text()).toContain('拖出范围');expect(w.find('.pin-categories').exists()).toBe(false);const board=w.findComponent({name:'BeadCanvas'});board.vm.$emit('select',{x:0,y:0,width:2,height:1});await w.vm.$nextTick();await button(w,'擦除');expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');expect(store.current!.cells[0]).toBeNull();await button(w,'撤销');expect(store.current!.cells).toEqual(original);w.unmount()})
 it('starts erasing with empty history even after a prior saved brush session',async()=>{const {w,store}=await setup();await button(w,'画笔');const board=w.findComponent({name:'BeadCanvas'}),c=[...store.current!.cells];c[7]='H7';board.vm.$emit('change',c);await w.vm.$nextTick();await button(w,'保存当前操作');await button(w,'橡皮');expect(w.find('[aria-label="撤销"]').attributes('disabled')).toBeDefined();const erased=[...c];erased[7]=null;board.vm.$emit('change',erased);await w.vm.$nextTick();await button(w,'保存当前操作');await button(w,'撤销');expect(store.current!.cells[7]).toBe('H7');w.unmount()})
 it('chooses a source type before generating and applies the preview as an independent canvas',async()=>{vi.useFakeTimers();vi.stubGlobal('Image',class{onload:()=>void=()=>{};naturalWidth=8;naturalHeight=8;set src(_:string){this.onload()}});vi.stubGlobal('Worker',class{onmessage:(e:unknown)=>void=()=>{};onerror=()=>{};terminate(){};postMessage(data:{id:number;width:number;height:number}){this.onmessage({data:{id:data.id,cells:Array(data.width*data.height).fill('H7')}})}});vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue({drawImage:vi.fn(),getImageData:()=>({data:new Uint8ClampedArray(52*52*9*4)})} as unknown as CanvasRenderingContext2D);URL.createObjectURL=vi.fn(()=>'blob:test');URL.revokeObjectURL=vi.fn();const {w,store}=await setup(),original=[...store.current!.cells];const file=w.find('input[type="file"]');Object.defineProperty(file.element,'files',{value:[new File(['photo'],'test.png',{type:'image/png'})]});await file.trigger('change');expect(w.text()).toContain('选择图片类型');expect(w.find('.pin-crop-overlay').exists()).toBe(false);await button(w,'照片／写实');expect(w.text()).toContain('52 × 52');await button(w,'裁剪');expect(w.find('.pin-crop-overlay').exists()).toBe(true);await button(w,'确认剪裁');expect(w.find('.pin-import-photo img').attributes('alt')).toBe('剪裁后的画面');expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');await vi.advanceTimersByTimeAsync(350);await w.vm.$nextTick();expect(w.text()).toContain('图纸预览');expect(store.current!.cells).toEqual(original);await button(w,'保存当前操作');await w.vm.$nextTick();expect(w.text()).not.toContain('图纸预览');expect(store.current!.width).toBe(52);expect(store.current!.height).toBe(52);expect(store.current!.cells.every(cell=>cell==='H7')).toBe(true);await button(w,'撤销');expect(store.current!.cells).toEqual(original);w.unmount()})
 it('selects source beads before replacing and supports a palette replacement',async()=>{const {w,store}=await setup();await button(w,'换色');expect(w.text()).toContain('先点选豆板');const board=w.findComponent({name:'BeadCanvas'});board.vm.$emit('focus',0);await w.vm.$nextTick();await w.findComponent({name:'ColorDock'}).vm.$emit('choose','H2');await w.vm.$nextTick();expect(store.current!.cells[0]).toBe('H7');await button(w,'保存当前操作');expect(store.current!.cells.slice(0,4)).toEqual(['H2','H2',null,'H2']);w.unmount()})
 it('restores brush and fill after choosing a palette color while picking',async()=>{const {w}=await setup();for(const label of ['画笔','填充']){await button(w,label);const dock=w.findComponent({name:'ColorDock'});dock.vm.$emit('pick');await w.vm.$nextTick();expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe('eyedropper');dock.vm.$emit('choose','A5');await w.vm.$nextTick();expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe(label==='画笔'?'pencil':'fill');expect(w.findComponent({name:'BeadCanvas'}).props('color')).toBe('A5');await button(w,'取消当前操作')}w.unmount()})

 it('undoes replacement choices and toggles original without committing',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'换色');w.findComponent({name:'BeadCanvas'}).vm.$emit('focus',0);await w.vm.$nextTick();const dock=w.findComponent({name:'ColorDock'});dock.vm.$emit('choose','A1');await w.vm.$nextTick();dock.vm.$emit('choose','A2');await w.vm.$nextTick();await button(w,'撤销');expect(dock.props('color')).toBe('A1');await button(w,'重做');expect(dock.props('color')).toBe('A2');await w.find('.pin-recolor-compare').trigger('keydown',{key:' '});expect(w.find('.pin-recolor-compare').attributes('aria-pressed')).toBe('true');expect(store.current!.cells).toEqual(original);await w.find('.pin-recolor-compare').trigger('keyup',{key:' '});await button(w,'保存当前操作');expect(store.current!.cells[0]).toBe('A2');w.unmount()})

 it('previews centered board resizing without changing saved data until confirmation',async()=>{const {w,store}=await setup();const original=[...store.current!.cells];await button(w,'编辑');await button(w,'豆板尺寸');await button(w,'58 × 58');const board=w.findComponent({name:'BeadCanvas'});expect(board.props('width')).toBe(58);expect(board.props('height')).toBe(58);expect(board.props('cells')[3*58+3]).toBe('H7');expect(store.current!.width).toBe(52);expect(store.current!.cells).toEqual(original);await button(w,'取消当前操作');expect(board.props('width')).toBe(52);await button(w,'豆板尺寸');await button(w,'58 × 58');await button(w,'保存当前操作');expect(store.current!.width).toBe(58);expect(store.current!.cells[3*58+3]).toBe('H7');w.unmount()})
 it('confirms clearing directly without entering an editing mode',async()=>{const {w,store}=await setup();await button(w,'编辑');await button(w,'清空');await w.vm.$nextTick();expect(w.find('.pin-mode-dock').exists()).toBe(false);expect(store.current!.cells.filter(Boolean)).toHaveLength(0);await button(w,'撤销');expect(store.current!.cells[0]).toBe('H7');w.unmount()})

 it('toggles the eraser inside a brush session and restores brush on color selection',async()=>{const {w}=await setup();await button(w,'画笔');const dock=w.findComponent({name:'ColorDock'});expect(dock.props('canErase')).toBe(true);dock.vm.$emit('erase');await w.vm.$nextTick();expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe('eraser');dock.vm.$emit('choose','A3');await w.vm.$nextTick();expect(w.findComponent({name:'BeadCanvas'}).props('tool')).toBe('pencil');w.unmount()})

})
