<script setup lang="ts">
import PhotoCrop, { type Crop } from '../PhotoCrop.vue'
import { showConfirmDialog,showToast } from '@/shared/feedback'
import { t } from '@/shared/i18n'
import { computed, nextTick, onMounted, onUnmounted, ref, shallowRef, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Icon as VanIcon, Button as VanButton, Field as VanField, Slider as VanSlider, Switch as VanSwitch, setToastDefaultOptions } from 'vant'
import { colorByCode, defaultSettings, palette, type BeadProject, type Tool } from '@/core/project'
import { useProjectStore } from '@/modules/projects/projectStore'
import BeadCanvas from '../BeadCanvas.vue'
import { vDragScroll } from '../dragScroll'
import { readSource, saveSource } from '../sourceImage'
import ExportPanel from '@/modules/home/HomeExport.vue'
import ColorDock from '../ColorDock.vue'
import ToolGlyph from '../ToolGlyph.vue'
import { similarColors } from '../engine/similarColors'
import { connected, fitImageToBoard, rectIndices, resizeCells, type Cells, type Rect } from '../engine/operations'
import { reduceColors } from '../engine/colors'
import '../studio.css'
setToastDefaultOptions({position:'top',className:'pin-toast',duration:1400})
const route=useRoute(),router=useRouter(),store=useProjectStore();store.open(String(route.params.id))
const project=computed(()=>store.current),settings=computed(()=>project.value?.settings||defaultSettings()),layer=computed(()=>project.value?.layers[0])
const board=ref<InstanceType<typeof BeadCanvas>|null>(null),tool=ref<Tool>('pan'),panel=ref(''),expanded=ref(false),busy=ref(false)
const category=ref('draw'),peeking=ref(false)
function changeCategory(value:string){endPeek();category.value=value;activate('pan')}
function startPeek(e:PointerEvent){if(e.button!==0)return;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);peeking.value=true;board.value?.beginPreview()}
function endPeek(){peeking.value=false;board.value?.endPreview()}
const history=shallowRef<BeadProject[]>([]),future=shallowRef<BeadProject[]>([])
const fileInput=ref<HTMLInputElement|null>(null),jsonInput=ref<HTMLInputElement|null>(null),refInput=ref<HTMLInputElement|null>(null)
const color=computed(()=>settings.value.color),search=ref(''),paletteTab=ref('used'),recolorScope=ref<'single'|'connected'|'all'>('all'),focused=ref(-1),targetColor=ref('H7')
const selected=ref<Rect|null>(null),clipboard=shallowRef<{rect:Rect;cells:Cells}|null>(null),placing=ref(false),moving=ref(false),placement=ref<Rect|null>(null)
const widthDraft=ref(project.value?.width||52),heightDraft=ref(project.value?.height||52),ratioLocked=ref(true),anchor=ref<'center'|'top-left'>('center')
const nameDraft=ref(project.value?.name||''),author=ref(''),exporting=ref(false)
const reference=ref(''),referenceVisible=ref(true),referenceOpacity=ref(.35),referenceScale=ref(1),referenceX=ref(0),referenceY=ref(0)
const sourceBlob=shallowRef<Blob|null>(null)
const imageUrl=ref(''),imageName=ref(''),image=shallowRef<HTMLImageElement|null>(null),targetWidth=ref(29),maxColors=ref(24),style=ref<'cartoon'|'realistic'>('cartoon'),removeBackground=ref(false),tolerance=ref(32)
const imageType=ref<'cartoon'|'photo'|null>(null)
const generating=ref(false),generationError=ref(''),candidate=shallowRef<{width:number;height:number;cells:Cells}|null>(null),allowedMode=ref(false),allowed=ref<string[]>([]),allowedSearch=ref('')
const reduceLimit=ref(16),protectedCodes=ref<string[]>([]),reduced=shallowRef<Cells|null>(null),compareOriginal=ref(false)
let worker:Worker|null=null,generationId=0,generationTimer:ReturnType<typeof setTimeout>|undefined,alive=true
let importAccepted=false
let importBackup:{url:string;name:string;blob:Blob|null;image:HTMLImageElement|null;type:'cartoon'|'photo'|null;width:number;max:number;style:'cartoon'|'realistic';background:boolean;tolerance:number;limited:boolean;allowed:string[];crop:Crop;rotation:number}|null=null
const importPaletteOpen=ref(false)
const cropRatio=ref<'free'|'square'>('free')
const rotation=ref(0)
const crop=ref<Crop>({x:0,y:0,width:1,height:1})
const cropDraft=ref<Crop>({x:0,y:0,width:1,height:1}),cropEditing=ref(false)
const singleImportPage=ref(false)
const importStage=ref<'photo'|'generating'|'preview'>('photo'),importPage=ref('')
const editStep=ref(''),referenceBackup=ref({opacity:.35,scale:1,x:0,y:0,visible:true,url:''})
const recolorUndo=ref<string[]>([]),recolorRedo=ref<string[]>([])
const mode=ref(''),modeCells=shallowRef<Cells|null>(null),modeUndo=shallowRef<Cells[]>([]),modeRedo=shallowRef<Cells[]>([]),recolorStep=ref('source'),recolorMethod=ref('similar')
const editItems=computed(()=>[{id:'resize',name:'豆板尺寸',icon:'expand-o'},{id:'mirror-x',name:'水平镜像',icon:'exchange'},{id:'mirror-y',name:'垂直镜像',icon:'exchange'},{id:'grid',name:{auto:'自动网格',off:'隐藏网格',always:'显示网格'}[settings.value.grid],icon:{auto:'apps-o',off:'closed-eye',always:'eye-o'}[settings.value.grid]},{id:'round',name:settings.value.round?'圆豆':'方豆',icon:settings.value.round?'circle':'square'},{id:'reference',name:'参考图',icon:'photo-o'},{id:'clear',name:'清空',icon:'delete-o'}])
function editAction(id:string){if(id==='clear'){void clearAll();return}if(id==='grid'){const grid=({auto:'off',off:'always',always:'auto'} as const)[settings.value.grid];setSetting('grid',grid);showToast({message:`已切换为${{auto:'自动网格',off:'隐藏网格',always:'显示网格'}[grid]}`,icon:'passed'});return}if(id==='round'){setSetting('round',!settings.value.round);showToast({message:settings.value.round?'已切换为圆豆':'已切换为方豆',icon:'passed'});return}if(id.startsWith('mirror-')){const p=project.value!,cells=p.cells.map((_,i)=>p.cells[(id==='mirror-y'?p.height-1-Math.floor(i/p.width):Math.floor(i/p.width))*p.width+(id==='mirror-x'?p.width-1-i%p.width:i%p.width)]);commit(cells);showToast(id==='mirror-x'?'已水平镜像':'已垂直镜像');return}enterMode(id);if(id==='resize'){ratioLocked.value=false;anchor.value='center'}}
const referencePeek=ref(false)
function startCompare(e:PointerEvent){if(e.button!==0)return;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);compareOriginal.value=true}
function endCompare(){compareOriginal.value=false}
function endReferencePeek(){referencePeek.value=false}
async function saveReference(){let url=reference.value;if(url.startsWith('blob:')){const blob=await (await fetch(url)).blob();url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob)})}setSetting('reference',{url,opacity:referenceOpacity.value,scale:referenceScale.value,x:referenceX.value,y:referenceY.value});mode.value='';referencePeek.value=false;if(store.flush())showToast('保存成功')}

const modeTitle=computed(()=>({pencil:'画笔',fill:'矩形填充',eraser:'橡皮',recolor:'换色',mirror:'镜像',resize:'豆板尺寸',grid:'网格',display:'显示',layer:'锁定图纸',clear:'清空图纸',reference:'参考图',reduce:'减少用色',select:'选区',cropBeads:'裁剪',importPlace:'放置图纸',import:imageType.value===null?'选择图片类型':importStage.value==='preview'?'图纸预览':importStage.value==='generating'?'正在生成':singleImportPage.value?({detail:'图案大小',colors:'色数',style:'图片类型'}[importPage.value]||'照片处理'):'照片处理'}[mode.value]||''))
const settingsDraft=ref({...settings.value}),layerDraft=ref({locked:false,visible:true})
const suggested=computed(()=>similarColors(project.value?.cells[focused.value]||color.value))
function enterMode(id:string){referencePeek.value=false;singleImportPage.value=false;recolorUndo.value=[];recolorRedo.value=[];compareOriginal.value=false;if(id==='import'){importAccepted=false;importBackup={url:imageUrl.value,name:imageName.value,blob:sourceBlob.value,image:image.value,type:imageType.value,width:targetWidth.value,max:maxColors.value,style:style.value,background:removeBackground.value,tolerance:tolerance.value,limited:allowedMode.value,allowed:[...allowed.value],crop:{...crop.value},rotation:rotation.value}}board.value?.cancel();panel.value='';mode.value=id;selected.value=null;placing.value=false;placement.value=null;editStep.value=id==='reference'?'photo':id==='resize'?'dimensions':'count';referenceBackup.value={opacity:referenceOpacity.value,scale:referenceScale.value,x:referenceX.value,y:referenceY.value,visible:referenceVisible.value,url:reference.value};reduced.value=null;modeCells.value=null;modeUndo.value=[];modeRedo.value=[];focused.value=-1;recolorStep.value='source';recolorMethod.value='similar';tool.value=id==='cropBeads'?'select':['pencil','fill','eraser','recolor','select'].includes(id)?id as Tool:'pan';settingsDraft.value={...settings.value};layerDraft.value={locked:!!layer.value?.locked,visible:layer.value?.visible!==false};widthDraft.value=project.value!.width;heightDraft.value=project.value!.height}
function exitMode(){board.value?.cancel();if(mode.value==='import'&&!importAccepted&&importBackup){crop.value={...importBackup.crop};rotation.value=importBackup.rotation;}if(mode.value==='reference'){referenceOpacity.value=referenceBackup.value.opacity;referenceScale.value=referenceBackup.value.scale;referenceX.value=referenceBackup.value.x;referenceY.value=referenceBackup.value.y;referenceVisible.value=referenceBackup.value.visible;if(reference.value!==referenceBackup.value.url){if(reference.value)URL.revokeObjectURL(reference.value);reference.value=referenceBackup.value.url}}importPaletteOpen.value=false;if(mode.value==='import'){generationId++;worker?.terminate();clearTimeout(generationTimer);generating.value=false;image.value=null;if(importBackup){if(importAccepted){if(importBackup.url&&importBackup.url!==imageUrl.value)URL.revokeObjectURL(importBackup.url)}else{if(imageUrl.value&&imageUrl.value!==importBackup.url)URL.revokeObjectURL(imageUrl.value);imageUrl.value=importBackup.url;imageName.value=importBackup.name;sourceBlob.value=importBackup.blob;targetWidth.value=importBackup.width;maxColors.value=importBackup.max;style.value=importBackup.style;removeBackground.value=importBackup.background;tolerance.value=importBackup.tolerance;allowedMode.value=importBackup.limited;allowed.value=importBackup.allowed}}candidate.value=null}selected.value=null;placing.value=false;placement.value=null;reduced.value=null;mode.value='';modeCells.value=null;focused.value=-1;tool.value='pan'}
function stroke(cells:Cells){if(mode.value==='import'&&candidate.value){modeUndo.value=[...modeUndo.value.slice(-39),[...candidate.value.cells]];modeRedo.value=[];candidate.value={...candidate.value,cells};return}if(mode.value){modeUndo.value=[...modeUndo.value.slice(-39),[...(modeCells.value||project.value!.cells)]];modeRedo.value=[];modeCells.value=cells}else commit(cells)}
function mirror(axis:string){const p=project.value!,source=modeCells.value||p.cells,r=selected.value||{x:0,y:0,width:p.width,height:p.height},cells=[...source];rectIndices(r,p.width).forEach(i=>{const x=i%p.width-r.x,y=Math.floor(i/p.width)-r.y;cells[i]=source[(r.y+(axis==='y'?r.height-1-y:y))*p.width+r.x+(axis==='x'?r.width-1-x:x)]});stroke(cells)}
async function saveMode(){if(mode.value==='importPlace'){if(!placement.value||!placementCells.value||placementCollision.value)return;commit(placementCells.value);exitMode();category.value='import';if(imageUrl.value)URL.revokeObjectURL(imageUrl.value);imageUrl.value='';image.value=null;sourceBlob.value=null;candidate.value=null;clipboard.value=null;if(store.flush())showToast('图纸已加入豆板');return;}if(mode.value==='cropBeads'){if(!placing.value){if(!selected.value)return;copySelection(false);modeCells.value=Array(project.value!.cells.length).fill(null);return}if(!placement.value||!placementCells.value)return;commit(placementCells.value);exitMode();category.value='import';showToast('保存成功');return;}if(mode.value==='import'){if(importStage.value==='photo'){if(!image.value)return;importStage.value='generating';scheduleGeneration();return}if(importStage.value==='preview'){await applyGeneration();return}return}if(mode.value==='select'&&placing.value){if(!placement.value||placementCollision.value)return;finishPlacement();return}if(mode.value==='reference'){try{await saveReference()}catch{showToast('保存失败，请重试或导出备份')}return}if(mode.value==='reduce'){if(!reduced.value)startReduction();if(!reduced.value)return;commit(reduced.value)}if(mode.value==='resize'){await applyResize();if(widthDraft.value!==project.value!.width||heightDraft.value!==project.value!.height)return}else if(mode.value==='clear'){await clearAll();if(total.value)return}else if(mode.value==='recolor'){if(focused.value<0)return;const c=[...project.value!.cells];recolorIndices.value.forEach(i=>c[i]=targetColor.value);commit(c)}else if(modeCells.value)commit(modeCells.value);if(['grid','display'].includes(mode.value))store.update({...project.value!,settings:{...settingsDraft.value}});if(mode.value==='layer')store.update({...project.value!,layers:[{...layer.value!,...layerDraft.value}]});exitMode();if(store.flush())showToast('保存成功')}
const counts=computed(()=>{const counts=new Map<string,number>();project.value?.cells.forEach(c=>{if(c)counts.set(c,(counts.get(c)||0)+1)});return counts})
const usage=computed(()=>palette.filter(c=>counts.value.has(c.code)).sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true})))
const total=computed(()=>[...counts.value.values()].reduce((a,b)=>a+b,0))
const filteredPalette=computed(()=>{const list=paletteTab.value==='used'?usage.value:paletteTab.value==='recent'?settings.value.recent.map(c=>colorByCode(c)).filter((c):c is typeof palette[number]=>Boolean(c)):palette;return list.filter(c=>`${c.code} ${c.name}`.toLowerCase().includes(search.value.toLowerCase()))})
const allowedPalette=computed(()=>palette.filter(c=>`${c.code} ${c.name}`.toLowerCase().includes(allowedSearch.value.toLowerCase())))
const recolorIndices=computed(()=>{const p=project.value,i=focused.value;if(!p||i<0||!p.cells[i])return[];return recolorScope.value==='single'?[i]:recolorScope.value==='connected'?connected(p.cells,p.width,i):p.cells.flatMap((c,j)=>c===p.cells[i]?[j]:[])})
const previewCells=computed(()=>{if(modeCells.value)return modeCells.value;if(reduced.value&&!compareOriginal.value)return reduced.value;if(mode.value==='recolor'&&focused.value>=0&&recolorStep.value==='target'&&!compareOriginal.value){const cells=[...project.value!.cells];recolorIndices.value.forEach(i=>cells[i]=targetColor.value);return cells}return project.value?.cells||[]})
const display=computed(()=>{if(mode.value==='resize'&&project.value){const width=Math.max(8,Math.min(180,Math.round(Number(widthDraft.value)||8))),height=Math.max(8,Math.min(180,Math.round(Number(heightDraft.value)||8)));return {width,height,cells:resizeCells(project.value.cells,project.value.width,width,height,'center')}}return (panel.value==='generate'||mode.value==='import'&&importStage.value==='preview')&&candidate.value?candidate.value:{width:project.value?.width||52,height:project.value?.height||52,cells:previewCells.value}})
const panelTitle=computed(()=>({colors:'选一个喜欢的颜色',settings:'图纸设置',usage:'用量统计',generate:'照片生成图纸',recolor:'替换颜色',reduce:'减少用色',export:'带走你的图纸',reference:'照片参考',rename:'给作品起个名字'}[panel.value]||''))
const tools:{id:Tool;label:string}[]=[{id:'pan',label:'浏览'},{id:'pencil',label:'画笔'},{id:'eraser',label:'橡皮'},{id:'fill',label:'填充'},{id:'recolor',label:'换色'},{id:'select',label:'选区'}]
const canvasContext=ref('')
const selectedIds=computed(()=>selected.value?rectIndices(selected.value,project.value!.width).filter(i=>(modeCells.value||project.value!.cells)[i]):[])
function selectBeads(r:Rect){const p=project.value!,ids=rectIndices(r,p.width).filter(i=>(modeCells.value||p.cells)[i]);if(!ids.length){selected.value=null;showToast('范围内没有拼豆');return}const xs=ids.map(i=>i%p.width),ys=ids.map(i=>Math.floor(i/p.width));selected.value={x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs)+1,height:Math.max(...ys)-Math.min(...ys)+1};showToast(`已选 ${ids.length} 颗拼豆`)}
watch(()=>store.saveState,state=>{if(state==='error')showToast('保存失败，请重试或导出备份')})

const effectiveLocked=computed(()=>Boolean(layer.value?.locked)||['generate','reduce','recolor'].includes(panel.value))
function snapshot(){return JSON.parse(JSON.stringify(project.value)) as BeadProject}
function commit(cells:Cells,width=project.value!.width,height=project.value!.height){const p=project.value;if(!p||layer.value?.locked)return;if(width===p.width&&height===p.height&&!cells.some((c,i)=>c!==p.cells[i]))return;history.value=[...history.value.slice(-39),snapshot()];future.value=[];store.update({...p,width,height,cells,layers:[{...p.layers[0],cells}]});selected.value=null;reduced.value=null;focused.value=-1;widthDraft.value=width;heightDraft.value=height}
type PhotoState={crop:Crop;rotation:number;type:'cartoon'|'photo'|null;width:number;colors:number;style:'cartoon'|'realistic';background:boolean;allowedMode:boolean;allowed:string[];ratio:'free'|'square'}
const photoUndo=ref<PhotoState[]>([]),photoRedo=ref<PhotoState[]>([]),photoBaseline=ref<PhotoState|null>(null)
let restoringPhoto=false,lastPhotoChange=0
function photoState():PhotoState{return {crop:{...crop.value},rotation:rotation.value,type:imageType.value,width:targetWidth.value,colors:maxColors.value,style:style.value,background:removeBackground.value,allowedMode:allowedMode.value,allowed:[...allowed.value],ratio:cropRatio.value}}
function resetPhotoHistory(){photoUndo.value=[];photoRedo.value=[];photoBaseline.value=photoState();lastPhotoChange=0}
function restorePhoto(s:PhotoState){restoringPhoto=true;crop.value={...s.crop};rotation.value=s.rotation;imageType.value=s.type;targetWidth.value=s.width;maxColors.value=s.colors;style.value=s.style;removeBackground.value=s.background;allowedMode.value=s.allowedMode;allowed.value=[...s.allowed];cropRatio.value=s.ratio;restoringPhoto=false;lastPhotoChange=0}
watch(photoState,(now,old)=>{if(restoringPhoto||mode.value!=='import'||importStage.value!=='photo')return;const time=Date.now();if(time-lastPhotoChange>300)photoUndo.value.push(old);lastPhotoChange=time;photoRedo.value=[]},{deep:true,flush:'sync'})
function photoChanged(id:string){const b=photoBaseline.value;if(!b)return false;const s=photoState();return id==='size'?JSON.stringify(s.crop)!==JSON.stringify(b.crop):id==='rotate'?s.rotation!==b.rotation:id==='detail'?s.width!==b.width:id==='colors'?s.colors!==b.colors:id==='style'?s.type!==b.type:id==='background'?s.background!==b.background:id==='palette'?s.allowedMode!==b.allowedMode||JSON.stringify(s.allowed)!==JSON.stringify(b.allowed):false}
function setCropRatio(value:'free'|'square'){cropRatio.value=value;if(value==='square'&&image.value){const ratio=rotation.value%180?image.value.naturalHeight/image.value.naturalWidth:image.value.naturalWidth/image.value.naturalHeight,c=crop.value,width=Math.min(c.width,c.height/ratio);crop.value={x:c.x+(c.width-width)/2,y:c.y+(c.height-width*ratio)/2,width,height:width*ratio}}}
function undo(){if(busy.value)return;if(mode.value==='recolor'){const previous=recolorUndo.value.pop();if(previous){recolorRedo.value.push(targetColor.value);targetColor.value=previous;compareOriginal.value=false}return;}if(mode.value==='import'&&importStage.value==='photo'){const previous=photoUndo.value.pop();if(previous){photoRedo.value.push(photoState());restorePhoto(previous)}return;}if(mode.value==='import'&&candidate.value){if(!modeUndo.value.length)return;modeRedo.value=[...modeRedo.value,[...candidate.value.cells]];candidate.value={...candidate.value,cells:modeUndo.value.at(-1)!};modeUndo.value=modeUndo.value.slice(0,-1);return}if(mode.value){if(!modeUndo.value.length)return;modeRedo.value=[...modeRedo.value,[...(modeCells.value||project.value!.cells)]];modeCells.value=modeUndo.value.at(-1)!;modeUndo.value=modeUndo.value.slice(0,-1);return}if(!history.value.length||busy.value||layer.value?.locked)return;future.value=[...future.value,snapshot()];const p=history.value[history.value.length-1]!;history.value=history.value.slice(0,-1);store.update({...project.value!,width:p.width,height:p.height,cells:p.cells,layers:p.layers});clearTransient()}
function redo(){if(busy.value)return;if(mode.value==='recolor'){const next=recolorRedo.value.pop();if(next){recolorUndo.value.push(targetColor.value);targetColor.value=next;compareOriginal.value=false}return;}if(mode.value==='import'&&importStage.value==='photo'){const next=photoRedo.value.pop();if(next){photoUndo.value.push(photoState());restorePhoto(next)}return;}if(mode.value==='import'&&candidate.value){if(!modeRedo.value.length)return;modeUndo.value=[...modeUndo.value,[...candidate.value.cells]];candidate.value={...candidate.value,cells:modeRedo.value.at(-1)!};modeRedo.value=modeRedo.value.slice(0,-1);return}if(mode.value){if(!modeRedo.value.length)return;modeUndo.value=[...modeUndo.value,[...(modeCells.value||project.value!.cells)]];modeCells.value=modeRedo.value.at(-1)!;modeRedo.value=modeRedo.value.slice(0,-1);return}if(!future.value.length||busy.value||layer.value?.locked)return;history.value=[...history.value,snapshot()];const p=future.value[future.value.length-1]!;future.value=future.value.slice(0,-1);store.update({...project.value!,width:p.width,height:p.height,cells:p.cells,layers:p.layers});clearTransient()}
function setSetting(key:string,value:unknown){if(project.value)store.update({...project.value,settings:{...settings.value,[key]:value}})}
function chooseColor(code:string){if(mode.value==='recolor'){if(code!==targetColor.value){recolorUndo.value.push(targetColor.value);recolorRedo.value=[];targetColor.value=code}compareOriginal.value=false;return}if(mode.value==='pencil'||mode.value==='fill')tool.value=mode.value;setSetting('color',code);setSetting('recent',[code,...settings.value.recent.filter(c=>c!==code)].slice(0,7))}
function activate(next:Tool){if(['pencil','fill','eraser','recolor','select'].includes(next)){enterMode(next);return}exitMode();board.value?.cancel();panel.value='';reduced.value=null;focused.value=-1;placing.value=false;placement.value=null;tool.value=next;if(next!=='select')selected.value=null}
function pick(code:string){showToast(`已选取 ${code} · ${colorByCode(code)?.name||''}`);if(mode.value==='recolor'){targetColor.value=code;recolorStep.value='target';tool.value='pan'}else{chooseColor(code);tool.value=mode.value==='fill'?'fill':'pencil'}}
function openPanel(next:string){board.value?.cancel();if(placing.value){placing.value=false;placement.value=null;tool.value='pan'}if(['generate','reduce'].includes(next))selected.value=null;reduced.value=null;compareOriginal.value=false;panel.value=panel.value===next?'':next;expanded.value=false;if(next==='colors'&&!usage.value.length)paletteTab.value='all';if(next==='generate'&&image.value)scheduleGeneration()}
function closePanel(){panel.value='';reduced.value=null;compareOriginal.value=false}
function clearTransient(){closePanel();selected.value=null;placing.value=false;placement.value=null;focused.value=-1;widthDraft.value=project.value!.width;heightDraft.value=project.value!.height}
function focus(index:number){if(!project.value?.cells[index])return;recolorUndo.value=[];recolorRedo.value=[];compareOriginal.value=false;focused.value=index;targetColor.value=project.value.cells[index]!;recolorStep.value='target';tool.value='recolor'}
function applyRecolor(){const cells=[...project.value!.cells],count=recolorIndices.value.length;recolorIndices.value.forEach(i=>cells[i]=targetColor.value);commit(cells);closePanel();showToast(`已替换 ${count} 颗拼豆`)}
function startReduction(){try{reduced.value=reduceColors(project.value!.cells,reduceLimit.value,protectedCodes.value);compareOriginal.value=false}catch(e){showToast((e as Error).message)}}
function toggleProtected(code:string){reduced.value=null;protectedCodes.value=protectedCodes.value.includes(code)?protectedCodes.value.filter(c=>c!==code):[...protectedCodes.value,code]}
function copySelection(move=false){if(!selected.value)return;clipboard.value={rect:{...selected.value},cells:rectIndices(selected.value,project.value!.width).map(i=>(modeCells.value||project.value!.cells)[i])};moving.value=move;placing.value=true;placement.value=null;tool.value='paste'}
const placementCells=computed(()=>{if(!placing.value||!placement.value||!clipboard.value)return null;const p=project.value!,c=[...(modeCells.value||p.cells)],r=placement.value;if(moving.value)rectIndices(clipboard.value.rect,p.width).forEach(i=>c[i]=null);clipboard.value.cells.forEach((v,i)=>{if(v)c[(r.y+Math.floor(i/r.width))*p.width+r.x+i%r.width]=v});return c})
const placementCollision=computed(()=>{if(!placement.value||!clipboard.value)return 0;const source=moving.value?new Set(rectIndices(clipboard.value.rect,project.value!.width)):new Set<number>();return clipboard.value.cells.reduce((sum,c,i)=>{const j=(placement.value!.y+Math.floor(i/placement.value!.width))*project.value!.width+placement.value!.x+i%placement.value!.width;return sum+(c&&(modeCells.value||project.value!.cells)[j]&&!source.has(j)?1:0)},0)})
function place(index:number){if(!clipboard.value)return;const r=clipboard.value.rect;placement.value={...r,x:Math.min(index%project.value!.width,project.value!.width-r.width),y:Math.min(Math.floor(index/project.value!.width),project.value!.height-r.height)}}
function finishPlacement(){if(placementCells.value){stroke(placementCells.value);selected.value=null;placing.value=false;tool.value='select';placement.value=null}}
function editSelection(action:'fill'|'clear'|'mirror-x'|'mirror-y'){if(!selected.value)return;const r=selected.value,p=project.value!,source=modeCells.value||p.cells,cells=[...source];rectIndices(r,p.width).forEach(i=>{const x=i%p.width-r.x,y=Math.floor(i/p.width)-r.y;cells[i]=action==='fill'?(source[i]?color.value:null):action==='clear'?null:p.cells[(r.y+(action==='mirror-y'?r.height-1-y:y))*p.width+r.x+(action==='mirror-x'?r.width-1-x:x)]});stroke(cells);selected.value=null;tool.value='select'}
function dimensionInput(axis:'width'|'height',value:string){const n=Number(value);if(axis==='width')widthDraft.value=n;else heightDraft.value=n;if(ratioLocked.value&&n>0){if(axis==='width')heightDraft.value=Math.round(n*project.value!.height/project.value!.width);else widthDraft.value=Math.round(n*project.value!.width/project.value!.height)}}
async function applyResize(){const p=project.value!,w=Math.round(Number(widthDraft.value)),h=Math.round(Number(heightDraft.value));if(w<8||w>180||h<8||h>180||!Number.isFinite(w+h))return showToast('宽高请输入 8–180 格');const cells=resizeCells(p.cells,p.width,w,h,anchor.value),lost=total.value-cells.filter(Boolean).length;if(lost>0){try{await showConfirmDialog({className:'pin-confirm',theme:'round-button',confirmButtonColor:'var(--animal-primary)',title:'缩小画布',message:`将裁掉 ${lost} 颗，可撤销。`})}catch{return}}commit(cells,w,h);closePanel();await nextTick();board.value?.fit()}
async function clearAll(){try{await showConfirmDialog({className:'pin-confirm',theme:'round-button',confirmButtonColor:'var(--animal-primary)',title:'清空图纸？',message:'清空全部拼豆，可撤销。'});commit(Array(project.value!.cells.length).fill(null));closePanel();if(store.flush())showToast('已清空图纸')}catch{}}
function lock(){if(project.value)store.update({...project.value,layers:[{...layer.value!,locked:!layer.value?.locked}]})}
function toggleVisible(){if(project.value)store.update({...project.value,layers:[{...layer.value!,visible:!layer.value?.visible}]})}
function loadImage(url:string){generationId++;image.value=null;candidate.value=null;generationError.value='';imageUrl.value=url;generating.value=true;const img=new Image();img.onload=()=>{if(alive&&imageUrl.value===url){image.value=img;generating.value=false;resetPhotoHistory();if(mode.value!=='import'||importStage.value!=='photo')scheduleGeneration()}};img.onerror=()=>{if(alive&&imageUrl.value===url){generating.value=false;generationError.value='图片读取失败，请重新选择'}};img.src=url}
function adjustGenerated(page:string){adjustSource();singleImportPage.value=true;importPage.value=page}
function adjustSource(){if(!imageUrl.value)return;enterMode('import');importStage.value='photo';importPage.value='';loadImage(imageUrl.value)}
function importPhoto(e:Event){const input=e.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type))return showToast('请选择 PNG、JPG 或 WebP 图片');enterMode('import');imageType.value=null;targetWidth.value=Math.min(29,project.value!.width);maxColors.value=16;style.value='cartoon';cropRatio.value='free';rotation.value=0;crop.value={x:0,y:0,width:1,height:1};cropDraft.value={...crop.value};cropEditing.value=false;sourceBlob.value=file;imageName.value=file.name;importStage.value='photo';importPage.value='';category.value='draw';loadImage(URL.createObjectURL(file));input.value=''}
function scheduleGeneration(){clearTimeout(generationTimer);generationId++;generationError.value='';if(!image.value)return;generating.value=true;const id=generationId;generationTimer=setTimeout(()=>generate(id),320)}
function orientedPhoto(){const img=image.value;if(!img)return null;if(!rotation.value)return img;const canvas=document.createElement('canvas'),odd=rotation.value%180!==0;canvas.width=odd?img.naturalHeight:img.naturalWidth;canvas.height=odd?img.naturalWidth:img.naturalHeight;const ctx=canvas.getContext('2d')!;ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation.value*Math.PI/180);ctx.drawImage(img,-img.naturalWidth/2,-img.naturalHeight/2);return canvas}
const processedPhoto=computed(()=>{const src=orientedPhoto();return src instanceof HTMLCanvasElement?src.toDataURL('image/png'):imageUrl.value})
function rotatePhoto(direction:number){const c=crop.value;crop.value=direction>0?{x:1-c.y-c.height,y:c.x,width:c.height,height:c.width}:{x:c.y,y:1-c.x-c.width,width:c.height,height:c.width};rotation.value=(rotation.value+direction*90+360)%360}
const generatedSize=computed(()=>{const img=image.value,p=project.value;if(!img||!p)return {width:1,height:1};const odd=rotation.value%180!==0;return fitImageToBoard((odd?img.naturalHeight:img.naturalWidth)*crop.value.width,(odd?img.naturalWidth:img.naturalHeight)*crop.value.height,p.width,p.height,targetWidth.value)});
const sizePresets=computed(()=>{const limit=Math.max(project.value!.width,project.value!.height);return (imageType.value==='photo'?[29,40,52]:[29,40,48]).filter(n=>n<=limit)})
function selectImageType(type:'cartoon'|'photo',page='detail'){
  imageType.value=type
  style.value=type==='cartoon'?'cartoon':'realistic'
  targetWidth.value=Math.min(type==='cartoon'?29:52,Math.max(project.value!.width,project.value!.height))
  maxColors.value=type==='cartoon'?16:32
  importPage.value=page
  resetPhotoHistory()
}
const croppedPhoto=computed(()=>{const src=orientedPhoto();if(!src||!image.value)return '';if(crop.value.x===0&&crop.value.y===0&&crop.value.width===1&&crop.value.height===1)return processedPhoto.value;const sw=src instanceof HTMLCanvasElement?src.width:image.value.naturalWidth,sh=src instanceof HTMLCanvasElement?src.height:image.value.naturalHeight,c=document.createElement('canvas');c.width=Math.max(1,Math.round(sw*crop.value.width));c.height=Math.max(1,Math.round(sh*crop.value.height));c.getContext('2d')!.drawImage(src,sw*crop.value.x,sh*crop.value.y,c.width,c.height,0,0,c.width,c.height);return c.toDataURL('image/png')})
function openCrop(){cropDraft.value={...crop.value};cropEditing.value=true}
function cancelCrop(){cropDraft.value={...crop.value};cropEditing.value=false}
function confirmCrop(){crop.value={...cropDraft.value};cropEditing.value=false;importPage.value='detail'}
function generate(id:number){if(!image.value)return;if(allowedMode.value&&!allowed.value.length){generationError.value='请至少选择一种允许使用的颜色';generating.value=false;return}try{const src=orientedPhoto()!,sw=src instanceof HTMLCanvasElement?src.width:image.value.naturalWidth,sh=src instanceof HTMLCanvasElement?src.height:image.value.naturalHeight;const dimensions=generatedSize.value,c=document.createElement('canvas');c.width=dimensions.width*3;c.height=dimensions.height*3;const ctx=c.getContext('2d')!;ctx.drawImage(src,sw*crop.value.x,sh*crop.value.y,sw*crop.value.width,sh*crop.value.height,0,0,c.width,c.height);const pixels=ctx.getImageData(0,0,c.width,c.height).data;worker?.terminate();worker=new Worker(new URL('../engine/generation.worker.ts',import.meta.url),{type:'module'});worker.onmessage=e=>{if(e.data.id!==generationId||!alive)return;generating.value=false;if(e.data.error)generationError.value=e.data.error;else {candidate.value={...dimensions,cells:e.data.cells};if(mode.value==='import'){importStage.value='preview';resetPhotoHistory();modeUndo.value=[];modeRedo.value=[];tool.value='pan'}}};worker.onerror=()=>{if(id===generationId){generating.value=false;generationError.value='生成失败，请重试'}};worker.postMessage({id,...dimensions,pixels,maxColors:maxColors.value,allowed:allowedMode.value?Array.from(allowed.value):[],style:style.value,removeBackground:removeBackground.value,tolerance:tolerance.value},[pixels.buffer])}catch{generating.value=false;generationError.value='无法处理这张图片，请重试或更换图片'}}
watch([targetWidth,maxColors,style,removeBackground,tolerance,allowedMode,allowed],()=>{if(image.value&&(mode.value!=='import'||importStage.value==='preview'))scheduleGeneration()},{deep:true})
function toggleAllowed(code:string){allowed.value=allowed.value.includes(code)?allowed.value.filter(c=>c!==code):[...allowed.value,code]}
async function applyGeneration(){if(!candidate.value||generating.value||generationError.value)return;const c=candidate.value,p=project.value!;if(!c.cells.some(Boolean)){showToast('图纸没有豆子，请调整后生成');return}if(p.cells.some(Boolean)){try{await showConfirmDialog({className:'pin-confirm',theme:'round-button',confirmButtonColor:'var(--animal-primary)',title:'应用新的生成结果',message:'将替换当前图纸与尺寸，原内容可通过撤销恢复。'})}catch{return}}importAccepted=true;commit(c.cells,c.width,c.height);exitMode();category.value='draw';await nextTick();board.value?.fit();if(store.flush())showToast('图纸已应用')}
async function exportFile(format:'pdf'|'png'|'json'|'xlsx'|'legacy'){exporting.value=true;const exportingProject=snapshot();try{await document.fonts.ready;const exporters=await import('../engine/export');if(format==='json'||format==='legacy')exporters.downloadJson(exportingProject,format==='legacy');else exporters.exportProject(exportingProject,format,author.value)}catch{showToast('导出失败，请重试')}finally{exporting.value=false}}
async function importJson(e:Event){const input=e.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{const raw=JSON.parse(await file.text());if(raw.activeBrand==='MARD'){const map=(c:string|null)=>c?.startsWith('mard-')?c.slice(5).toUpperCase():c;raw.cells=raw.cells?.map(map);raw.layers=raw.layers?.map((l:object & {cells:Cells})=>({...l,type:'bead',cells:l.cells.map(map)}))}const imported=store.importProject(raw);await router.push(`/studio/${imported.id}`)}catch(e){showToast((e as Error).message||'文件无效，当前作品未改动')}input.value=''}
function importReference(e:Event){const input=e.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(reference.value&&reference.value!==referenceBackup.value.url)URL.revokeObjectURL(reference.value);reference.value=URL.createObjectURL(file);referenceVisible.value=true;if(mode.value!=='reference')enterMode('reference');input.value=''}
function rename(){const name=nameDraft.value.trim();if(name&&project.value){store.update({...project.value,name});closePanel();if(store.flush())showToast('名称已保存')}}
async function leave(){board.value?.cancel();if(!store.flush()){showToast('本地保存失败，请先导出 JSON 备份');panel.value='export';return}await router.push('/')}
watch(()=>route.params.id,id=>{store.open(String(id));history.value=[];future.value=[];clearTransient();nextTick(()=>board.value?.fit())})
onMounted(async()=>{window.addEventListener('blur',endPeek);window.addEventListener('blur',endCompare);if(!project.value){router.replace('/');return}if(layer.value?.locked||layer.value?.visible===false)store.update({...project.value,layers:[{...layer.value!,locked:false,visible:true}]});const savedRef=settings.value.reference;if(savedRef){reference.value=savedRef.url;referenceOpacity.value=savedRef.opacity;referenceScale.value=savedRef.scale;referenceX.value=savedRef.x;referenceY.value=savedRef.y}const url=sessionStorage.getItem(`pocket-pin:import:${project.value.id}`);if(url){sessionStorage.removeItem(`pocket-pin:import:${project.value.id}`);imageName.value=project.value.name;enterMode('import');importStage.value='photo';importPage.value='';try{sourceBlob.value=await (await fetch(url)).blob()}catch{}loadImage(url)}})
onUnmounted(()=>{if(project.value)store.discardEmptyDraft(project.value.id);window.removeEventListener('blur',endPeek);window.removeEventListener('blur',endCompare);endPeek();alive=false;generationId++;clearTimeout(generationTimer);worker?.terminate();if(imageUrl.value)URL.revokeObjectURL(imageUrl.value);if(reference.value)URL.revokeObjectURL(reference.value);store.flush()})
</script>

<template>
<div v-if="project" class="pin-studio">
  <header class="pin-header">
    <van-button class="pin-icon-button" :aria-label="t('返回图纸空间')" @click="leave"><van-icon name="arrow-left"/></van-button>
    <van-button class="pin-project-name" @click="nameDraft=project.name;openPanel('rename')">{{ project.name }}</van-button>

    <van-button v-if="!mode&&!selected&&!placing&&(!panel||panel==='usage'||panel==='export')" class="pin-usage-trigger" :aria-expanded="panel==='usage'" @click="openPanel('usage')">{{ t('用量') }}<van-icon :name="panel==='usage'?'arrow-up':'arrow-down'"/></van-button>
    <van-button v-if="!mode&&!selected&&!placing&&(!panel||panel==='usage'||panel==='export')" class="pin-export-trigger" type="primary" @click="openPanel('export')"><span>{{ t('导出') }}</span></van-button>
  </header>
  <div class="pin-summary"><span>{{ t(display.width) }} × {{ t(display.height) }}{{ t(' 格 · ') }}{{ t(total) }}{{ t(' 颗 · ') }}{{ t(usage.length) }}{{ t(' 色') }}</span><span class="pin-context">{{ t(selected?`已选 ${selectedIds.length} 颗拼豆`:['pencil','eraser'].includes(tool)?canvasContext:'') }}</span></div>
  <main class="pin-workspace" :class="{'has-panel':panel&&!['usage','export','rename'].includes(panel),'panel-expanded':expanded}">

    <section class="pin-canvas-region">
      <bead-canvas ref="board" :width="display.width" :height="display.height" :cells="placementCells||display.cells" :tool="panel==='generate'||panel==='reduce'||panel==='recolor'?'pan':tool" :color="color" :grid="mode==='grid'?settingsDraft.grid:settings.grid" :coordinates="mode==='display'?settingsDraft.coordinates:settings.coordinates" :boards="mode==='display'?settingsDraft.boards:settings.boards" :codes="mode==='display'?settingsDraft.codes:settings.codes" :round="mode==='display'?settingsDraft.round:settings.round" :reference-editing="mode==='reference'" :bead-opacity="mode==='reference'?.45:1" :visible="mode==='reference'?referencePeek:layer?.visible" @reference-transform="referenceScale=$event.scale;referenceX=$event.x;referenceY=$event.y" :locked="effectiveLocked" :clean-selection="mode==='cropBeads'" :selection="placement||selected" :highlights="mode==='recolor'?recolorIndices:selectedIds" :reference="referenceVisible&&panel!=='generate'?reference:''" :reference-opacity="referenceOpacity" :reference-scale="referenceScale" :reference-x="referenceX" :reference-y="referenceY" @change="stroke" @pick="pick" @focus="focus" @select="selectBeads" @context="canvasContext=$event" @place="place" @busy="busy=$event"/>
      <div v-if="mode==='import'&&importStage!=='preview'" class="pin-import-photo"><img v-if="croppedPhoto" :src="croppedPhoto" :alt="t('剪裁后的画面')"/><span v-if="generating">{{ t(importStage==='photo'?'正在读取照片…':'正在生成图纸…') }}</span></div>
      <div v-if="(panel==='generate'||mode==='import')&&generating" class="pin-status" role="status">{{ t('正在生成预览…') }}</div>
      <div v-if="layer?.locked" class="pin-lock-note">{{ t('图纸已锁定') }}</div>
    <div class="pin-history pin-board-history"><van-button class="pin-icon-button" :aria-label="t('撤销')" :title="t('撤销')" :disabled="!(mode==='recolor'?recolorUndo.length:mode==='import'&&importStage==='photo'?photoUndo.length:mode?modeUndo.length:history.length)||busy||!!layer?.locked" @click="undo"><van-icon name="revoke"/></van-button><van-button class="pin-icon-button" :aria-label="t('重做')" :title="t('重做')" :disabled="!(mode==='recolor'?recolorRedo.length:mode==='import'&&importStage==='photo'?photoRedo.length:mode?modeRedo.length:future.length)||busy||!!layer?.locked" @click="redo"><van-icon name="replay"/></van-button></div><van-button v-if="mode==='reference'" class="pin-icon-button pin-peek" :aria-label="t('按住查看拼豆效果')" @pointerdown.prevent="referencePeek=true;($event.currentTarget as HTMLElement).setPointerCapture($event.pointerId)" @pointerup="endReferencePeek" @pointercancel="endReferencePeek" @lostpointercapture="endReferencePeek" @blur="endReferencePeek" @keydown.space.prevent="referencePeek=true" @keyup.space.prevent="endReferencePeek"><tool-glyph name="mirror"/></van-button><van-button v-if="mode==='recolor'&&focused>=0" class="pin-icon-button pin-peek pin-recolor-compare" :aria-label="t('按住查看原图')" :aria-pressed="compareOriginal" @pointerdown.prevent="startCompare" @pointerup="endCompare" @pointercancel="endCompare" @lostpointercapture="endCompare" @blur="endCompare" @contextmenu.prevent @keydown.space.prevent="compareOriginal=true" @keyup.space.prevent="endCompare" @keydown.enter.prevent="compareOriginal=true" @keyup.enter.prevent="endCompare"><tool-glyph name="mirror"/></van-button><van-button v-if="!mode&&!selected&&!placing&&!panel" class="pin-icon-button pin-peek" :aria-label="t('按住预览整体，松开恢复')" :title="t('按住预览整体，松开恢复')" :aria-pressed="peeking" @pointerdown.prevent="startPeek" @pointerup="endPeek" @pointercancel="endPeek" @lostpointercapture="endPeek" @contextmenu.prevent @keydown.space.prevent="peeking=true;board?.beginPreview()" @keyup.space.prevent="endPeek" @blur="endPeek"><van-icon name="eye-o"/></van-button>
    </section>
    <div v-if="['usage','export','rename'].includes(panel)" class="pin-usage-overlay" @click="closePanel"></div>
    <Transition name="pin-panel-motion"><aside v-if="panel" class="pin-panel" :class="{'pin-usage-dropdown':['usage','export'].includes(panel),'pin-rename-sheet':panel==='rename'}" :role="panel==='usage'?'dialog':undefined" :aria-label="panelTitle">
      <div class="pin-panel-heading" v-if="!['rename','usage','export'].includes(panel)"><h2>{{ t(panelTitle) }}</h2><van-button class="pin-expand" @click="expanded=!expanded">{{ t(expanded?'收起':'展开') }}</van-button><van-button v-if="panel!=='usage'" class="pin-icon-button" :aria-label="t('关闭面板')" @click="closePanel"><van-icon name="cross"/></van-button></div>
      <div class="pin-panel-content">
        <template v-if="panel==='colors'||panel==='recolor'">
          <template v-if="panel==='recolor'"><p>{{ t('原色 ') }}{{ t(project.cells[focused]) }}{{ t(' · 影响 ') }}{{ t(recolorIndices.length) }}{{ t(' 颗') }}</p><div class="pin-segments"><van-button v-for="option in [{id:'single',label:'单格'},{id:'connected',label:'相连同色'},{id:'all',label:'全图同色'}]" :key="option.id" :class="{chosen:recolorScope===option.id}" @click="recolorScope=option.id as typeof recolorScope">{{ t(option.label) }}</van-button></div><p>{{ t('目标色 ') }}{{ t(targetColor) }}{{ t('，画布中可预览换色效果。') }}</p><div class="pin-actions"><van-button @click="compareOriginal=!compareOriginal">{{ t(compareOriginal?'看换色结果':'看原图') }}</van-button><van-button type="primary" @click="applyRecolor">{{ t('应用换色') }}</van-button></div></template>
          <div class="pin-segments"><van-button v-for="tab in [{id:'used',label:'本图用色'},{id:'recent',label:'最近'},{id:'all',label:'全部'}]" :key="tab.id" :class="{chosen:paletteTab===tab.id}" @click="paletteTab=tab.id">{{ t(tab.label) }}</van-button></div>
          <van-field v-model="search" :placeholder="t('搜索色号或名称，例如 H7')" :aria-label="t('搜索色号')"/>
          <div class="pin-swatches"><van-button v-for="c in filteredPalette" :key="c.code" :aria-label="`${c.code} ${c.name}`" :aria-pressed="(panel==='recolor'?targetColor:color)===c.code" :class="{chosen:(panel==='recolor'?targetColor:color)===c.code}" @click="chooseColor(c.code)"><i :style="{'--bead-color':c.hex}"></i><b>{{ t(c.code) }}</b><small v-if="counts.has(c.code)">{{ t(counts.get(c.code)) }}{{ t(' 颗') }}</small></van-button></div><p v-if="!filteredPalette.length">{{ t('这里还没有颜色，试试全部色卡。') }}</p>
        </template>
        <template v-if="panel==='generate'">
          <div class="pin-source"><img v-if="imageUrl" :src="imageUrl" alt="完整原图"><div><b>{{ t(imageName||'选择一张照片') }}</b><van-button @click="fileInput?.click()">{{ t(imageUrl?'更换图片':'选择图片') }}</van-button></div></div>
          <van-field :model-value="targetWidth" type="digit" :label="t('目标宽度')" right-icon="" @update:model-value="targetWidth=Math.max(8,Math.min(180,Number($event)||8))"/><p>{{ t('保持原图比例，最长边不超过 180 格。') }}</p>
          <div class="pin-segments"><van-button v-for="n in [26,52,78,104,156]" :key="n" :class="{chosen:targetWidth===n}" @click="targetWidth=n">{{ t(n) }}{{ t(' 格') }}</van-button></div>
          <label class="pin-range">{{ t('最多 ') }}{{ t(maxColors) }}{{ t(' 色') }}<van-slider v-model="maxColors" :min="2" :max="48" :step="1" :aria-label="t('生成色数上限')"/></label><div class="pin-segments"><van-button v-for="n in [8,12,16,24,32]" :key="n" :class="{chosen:maxColors===n}" @click="maxColors=n">{{ t(n) }}{{ t(' 色') }}</van-button></div>
          <div class="pin-segments"><van-button :class="{chosen:style==='cartoon'}" @click="style='cartoon'">{{ t('色块优先') }}</van-button><van-button :class="{chosen:style==='realistic'}" @click="style='realistic'">{{ t('自然还原') }}</van-button></div>
          <div class="pin-setting"><span>{{ t('去除近似背景色') }}</span><van-switch v-model="removeBackground" size="24px" :aria-label="t('去除背景')"/></div><label v-if="removeBackground" class="pin-range">{{ t('背景容差 ') }}{{ t(tolerance) }}<van-slider v-model="tolerance" :min="0" :max="120"/></label>
          <div class="pin-setting"><span>{{ t('只用我选择的色号') }}</span><van-switch v-model="allowedMode" size="24px" :aria-label="t('自选可用色号')"/></div>
          <template v-if="allowedMode"><p>{{ t('已选择 ') }}{{ t(allowed.length) }}{{ t(' 色') }}</p><div class="pin-actions"><van-button @click="allowed=usage.map(c=>c.code)">{{ t('使用本图颜色') }}</van-button><van-button @click="allowed=[]">{{ t('清除选择') }}</van-button></div><van-field v-model="allowedSearch" :placeholder="t('搜索允许使用的色号')"/><div class="pin-swatches pin-allowed"><van-button v-for="c in allowedPalette" :key="c.code" :class="{chosen:allowed.includes(c.code)}" :aria-pressed="allowed.includes(c.code)" @click="toggleAllowed(c.code)"><i :style="{'--bead-color':c.hex}"></i>{{ t(c.code) }}</van-button></div></template>
          <p v-if="generationError" role="alert">{{ t(generationError) }} <van-button @click="scheduleGeneration">{{ t('重试') }}</van-button></p>
          <div v-if="candidate" class="pin-result"><b>{{ t(candidate.width) }} × {{ t(candidate.height) }}{{ t(' 格') }}</b><span>{{ t('上限 ') }}{{ t(maxColors) }}{{ t(' 色 · 实际 ') }}{{ t(new Set(candidate.cells.filter(Boolean)).size) }}{{ t(' 色') }}</span></div>
          <van-button type="primary" block :disabled="!candidate||generating||!!generationError||!!layer?.locked" :loading="generating" @click="applyGeneration">{{ t(total?'应用到图纸':'开始编辑') }}</van-button><p>{{ t('预览不会修改当前作品，应用后才保存。') }}</p>
        </template>
        <template v-if="panel==='settings'">
          <h3>{{ t('图纸大小') }}</h3><div class="pin-dimensions"><van-field :model-value="widthDraft" type="digit" :label="t('宽')" @update:model-value="dimensionInput('width',$event)"/><van-field :model-value="heightDraft" type="digit" :label="t('高')" @update:model-value="dimensionInput('height',$event)"/></div>
          <div class="pin-setting"><span>{{ t('锁定当前宽高比') }}</span><van-switch v-model="ratioLocked" size="24px"/></div><div class="pin-segments"><van-button v-for="n in [52,78,104,156]" :key="n" @click="widthDraft=heightDraft=n">{{ t(n) }} × {{ t(n) }}</van-button></div>
          <div class="pin-segments"><van-button :class="{chosen:anchor==='center'}" @click="anchor='center'">{{ t('居中保留') }}</van-button><van-button :class="{chosen:anchor==='top-left'}" @click="anchor='top-left'">{{ t('左上对齐') }}</van-button></div><van-button :disabled="!!layer?.locked" @click="applyResize">{{ t('应用尺寸') }}</van-button>
          <h3>{{ t('画布显示') }}</h3><p>{{ t('缩小看轮廓，放大看格子。') }}</p><div class="pin-segments"><van-button v-for="o in [{id:'auto',label:'自动网格'},{id:'off',label:'关闭'},{id:'always',label:'始终显示'}]" :key="o.id" :class="{chosen:settings.grid===o.id}" @click="setSetting('grid',o.id)">{{ t(o.label) }}</van-button></div>
          <div v-for="o in [{id:'coordinates',label:'边缘坐标'},{id:'boards',label:'52 格拼豆板边界'},{id:'codes',label:'放大时显示色号'},{id:'round',label:'放大时显示圆豆'}]" :key="o.id" class="pin-setting"><span>{{ t(o.label) }}</span><van-switch :model-value="settings[o.id as keyof typeof settings] as boolean" size="24px" @update:model-value="setSetting(o.id,$event)"/></div>
          <div class="pin-setting"><span>{{ t('锁定图纸') }}</span><van-switch :model-value="!!layer?.locked" size="24px" @update:model-value="lock"/></div><div class="pin-setting"><span>{{ t('显示拼豆') }}</span><van-switch :model-value="layer?.visible!==false" size="24px" @update:model-value="toggleVisible"/></div>
          <div class="pin-actions"><van-button @click="openPanel('reference')">{{ t('参考照片') }}</van-button><van-button @click="openPanel('reduce')">{{ t('减少用色') }}</van-button></div><van-button type="danger" :disabled="!!layer?.locked||!total" @click="clearAll">{{ t('清空图纸') }}</van-button>
        </template>
        <template v-if="panel==='reduce'"><p>{{ t('保留主要颜色，将其他颜色合并到相近色。可以保护眼睛、描边等关键色。') }}</p><label class="pin-range">{{ t('最多 ') }}{{ t(reduceLimit) }}{{ t(' 色') }}<van-slider v-model="reduceLimit" :min="1" :max="Math.max(2,usage.length)" @update:model-value="reduced=null"/></label><div class="pin-swatches"><van-button v-for="c in usage" :key="c.code" :class="{chosen:protectedCodes.includes(c.code)}" :aria-pressed="protectedCodes.includes(c.code)" @click="toggleProtected(c.code)"><i :style="{'--bead-color':c.hex}"></i>{{ t(c.code) }}<small>{{ t(protectedCodes.includes(c.code)?'已保护':'保护此色') }}</small></van-button></div><van-button :disabled="!total||!!layer?.locked" @click="startReduction">{{ t('预览减少用色') }}</van-button><template v-if="reduced"><p>{{ t(usage.length) }}{{ t(' 色 → ') }}{{ t(new Set(reduced.filter(Boolean)).size) }}{{ t(' 色') }}</p><div class="pin-actions"><van-button @click="compareOriginal=!compareOriginal">{{ t(compareOriginal?'看处理结果':'看原图') }}</van-button><van-button type="primary" @click="commit(reduced);closePanel()">{{ t('应用') }}</van-button></div></template></template>
        <template v-if="panel==='reference'"><p>{{ t('照片仅用于当前会话，不计入拼豆材料或导出图纸。') }}</p><van-button @click="refInput?.click()">{{ t('选择参考照片') }}</van-button><template v-if="reference"><div class="pin-setting"><span>{{ t('显示参考图') }}</span><van-switch v-model="referenceVisible" size="24px"/></div><label class="pin-range">{{ t('透明度 ') }}{{ t(Math.round(referenceOpacity*100)) }}%<van-slider v-model="referenceOpacity" :min="0" :max="1" :step=".01"/></label><label class="pin-range">{{ t('缩放 ') }}{{ t(referenceScale.toFixed(1)) }}{{ t(' 倍') }}<van-slider v-model="referenceScale" :min=".1" :max="3" :step=".1"/></label><van-field v-model.number="referenceX" type="number" :label="t('横向偏移格数')"/><van-field v-model.number="referenceY" type="number" :label="t('纵向偏移格数')"/><van-button @click="referenceScale=1;referenceX=referenceY=0">{{ t('重置位置') }}</van-button></template></template>
        <template v-if="panel==='usage'"><div class="pin-usage-summary"><b>{{ t(total) }}{{ t(' 颗 · ') }}{{ t(usage.length) }}{{ t(' 色') }}</b><label><input :aria-label="t('每包颗数')" type="number" min="1" max="10000" :value="settings.beadsPerPack" @change="setSetting('beadsPerPack',Math.max(1,Math.min(10000,Number(($event.target as HTMLInputElement).value)||1)))"/>{{ t(' 颗/包 · 预计 ') }}{{ t(usage.reduce((s,c)=>s+Math.ceil(counts.get(c.code)!/settings.beadsPerPack),0)) }}{{ t(' 包') }}</label></div><div class="pin-usage"><div v-for="c in usage" :key="c.code"><i :style="{'--bead-color':c.hex}"></i><b>{{ t(c.code) }}</b><span>{{ t(counts.get(c.code)) }}{{ t(' 颗') }}</span><span>{{ t(Math.ceil(counts.get(c.code)!/settings.beadsPerPack)) }}{{ t(' 包') }}</span></div></div></template>
        <template v-if="panel==='export'"><div class="pin-studio-export"><export-panel :project="project"/></div></template>
        <template v-if="panel==='rename'"><van-field v-model="nameDraft" :placeholder="t('给作品起个名字')" maxlength="60" :aria-label="t('作品名称')" @keydown.enter="rename"/><div class="pin-operation-footer"><van-button class="pin-icon-button" :aria-label="t('取消改名')" @click="closePanel"><van-icon name="cross"/></van-button><b>{{ t('作品名称') }}</b><van-button class="pin-icon-button" :aria-label="t('保存名称')" :disabled="!nameDraft.trim()" @click="rename"><van-icon name="success"/></van-button></div></template>
      </div>
    </aside></Transition>
  </main>
  <div v-if="(selected||placing)&&!mode" class="pin-operation-dock">
    <nav v-if="!placing" class="pin-tools"><van-button v-for="a in [{id:'move',icon:'exchange',name:'移动'},{id:'copy',icon:'description',name:'复制'},{id:'fill',icon:'brush-o',name:'填色'},{id:'mirror',icon:'exchange',name:'镜像'},{id:'clear',icon:'delete-o',name:'擦除'}]" :key="a.id" :aria-label="a.name" @click="a.id==='move'?copySelection(true):a.id==='copy'?copySelection():a.id==='mirror'?enterMode('mirror'):editSelection(a.id as 'fill'|'clear'|'mirror-x'|'mirror-y')"><van-icon :name="a.icon"/><span>{{ t(a.name) }}</span></van-button></nav>
    <p v-else>{{ t(placementCollision?`与 ${placementCollision} 颗拼豆重叠，请换个位置`:'点击豆板选择落点') }}</p>
    <div class="pin-operation-footer"><van-button class="pin-icon-button" :aria-label="t('返回上一层')" @click="placing?(placing=false,placement=null,tool='select'):selected=null"><van-icon name="arrow-left"/></van-button><b>{{ t(placing?(moving?'移动拼豆':'复制拼豆'):'选区编辑') }}</b><van-button class="pin-icon-button" :aria-label="t('确认操作')" :disabled="placing&&(!placement||placementCollision>0)" @click="placing?finishPlacement():selected=null"><van-icon name="success"/></van-button></div>
  </div>
  <div v-if="category==='draw'&&!selected&&!placing&&!mode" class="pin-draw-dock">
    <color-dock v-if="['pencil','fill','eyedropper'].includes(tool)" :color="color" :can-pick="tool!=='fill'" @choose="chooseColor" @pick="tool='eyedropper'"/>

    <nav v-drag-scroll class="pin-tools" :aria-label="t('编辑工具')"><van-button v-for="item in tools" :key="item.id" :class="{chosen:tool===item.id}" :aria-pressed="tool===item.id" :disabled="!!layer?.locked&&!['pan','eyedropper'].includes(item.id)" @click="activate(item.id)"><tool-glyph :name="item.id==='select'?'copy':item.id"/><span>{{ t(item.label) }}</span></van-button></nav>  </div>
  <nav v-drag-scroll v-if="category==='edit'&&!mode" class="pin-edit-menu" :aria-label="t('豆板编辑')"><van-button v-for="item in editItems" :key="item.id" :aria-label="item.name" @click="editAction(item.id)"><tool-glyph v-if="item.id.startsWith('mirror-')" name="mirror" :style="{transform:item.id==='mirror-y'?'rotate(90deg)':undefined}"/><tool-glyph v-else-if="item.icon==='square'" name="square"/><van-icon v-else :name="item.icon"/><span>{{ t(item.name) }}</span></van-button></nav>
  <nav v-if="category==='import'&&!mode" class="pin-edit-menu pin-import-menu" :aria-label="t('导入图片')"><van-button class="pin-empty-import" :aria-label="t('选择图片')" @click="fileInput?.click()"><tool-glyph name="import"/><span>{{t('选择图片')}}</span></van-button></nav>
  <footer v-if="!selected&&!placing&&!mode" class="pin-categories" :aria-label="t('功能分类')"><van-button v-for="item in [{id:'draw',name:'绘图'},{id:'import',name:'导入'},{id:'edit',name:'编辑'}]" :key="item.id" :class="{chosen:category===item.id}" :aria-pressed="category===item.id" @click="changeCategory(item.id)">{{ t(item.name) }}</van-button></footer>
  <Transition name="pin-mode"><section v-if="mode" :key="mode" class="pin-mode-dock" :aria-label="modeTitle">
    <div class="pin-mode-controls">
      <template v-if="['pencil','fill','eraser'].includes(mode)"><p>{{ t(tool==='eyedropper'?'点击豆板上的豆子取色':mode==='fill'?'拖出矩形，松手填充':tool==='eraser'?'拖动擦除豆子':'单指画豆子，双指缩放与移动') }}</p><color-dock v-if="mode!=='eraser'" :color="color" :can-pick="true" :can-erase="mode==='pencil'" :erasing="tool==='eraser'" @erase="tool=tool==='eraser'?'pencil':'eraser'" @choose="chooseColor" @pick="tool='eyedropper'"/></template>
      <div v-if="mode==='recolor'" class="pin-recolor-controls">
        <p v-if="focused<0">{{ t('先点选豆板上要替换的颜色，再选择新的颜色') }}</p>
        <template v-else><p>{{ t(project.cells[focused]) }} → {{ t(targetColor) }} · {{ t(recolorIndices.length) }}{{ t(' 颗') }}</p><color-dock :key="focused" :color="targetColor" :can-pick="false" :recommended="suggested" default-recommended @choose="chooseColor"/>
        <div v-drag-scroll class="pin-recolor-scope" :aria-label="t('替换范围')"><van-button v-for="o in [{id:'single',name:'单颗'},{id:'connected',name:'相连'},{id:'all',name:'全图同色'}]" :key="o.id" :class="{chosen:recolorScope===o.id}" @click="recolorScope=o.id as typeof recolorScope">{{ t(o.name) }}</van-button></div></template>
      </div>
      <template v-if="mode==='importPlace'"><p>{{t(placementCollision?'此处已有豆子，请换个位置':'拖动图案选择位置，确认后加入豆板')}}</p></template><template v-if="mode==='cropBeads'"><p>{{t(placing?'拖动豆子选择位置，确认后放置':'拖出范围，保留选中的豆子')}}</p><van-button v-if="placing" class="pin-recrop" @click="placing=false;placement=null;modeCells=null;selected=null;tool='select'">{{t('重新裁剪')}}</van-button></template>
      <template v-if="mode==='select'"><p v-if="!selected&&!placing">{{ t('拖出范围，选择需要编辑的豆子') }}</p><template v-else-if="placing"><p>{{ t(placementCollision?`与 ${placementCollision} 颗重叠，请换个位置`:'点击豆板选择落点，再确认放置') }}</p><div class="pin-mode-options"><van-button @click="placing=false;placement=null;tool='select'">{{ t('返回选区') }}</van-button><van-button :disabled="!placement||placementCollision>0" @click="finishPlacement">{{ t('确认放置') }}</van-button></div></template><nav v-else v-drag-scroll class="pin-tools" :aria-label="t('选区操作')"><van-button v-for="a in [{id:'move',icon:'exchange',name:'移动'},{id:'copy',icon:'description',name:'复制'},{id:'fill',icon:'brush-o',name:'填色'},{id:'mirror-x',icon:'exchange',name:'水平镜像'},{id:'mirror-y',icon:'sort',name:'垂直镜像'},{id:'clear',icon:'delete-o',name:'擦除'}]" :key="a.id" :aria-label="a.name" @click="a.id==='move'?copySelection(true):a.id==='copy'?copySelection():a.id==='mirror-x'?mirror('x'):a.id==='mirror-y'?mirror('y'):editSelection(a.id as 'fill'|'clear')"><van-icon :name="a.icon"/><span>{{ t(a.name) }}</span></van-button></nav></template>
      <nav v-if="mode==='mirror'" class="pin-tools pin-mirror-menu" :aria-label="t('镜像操作')"><van-button :aria-label="t('水平镜像')" @click="mirror('x')"><tool-glyph name="mirror"/><span>{{ t('水平镜像') }}</span></van-button><van-button :aria-label="t('垂直镜像')" @click="mirror('y')"><tool-glyph name="mirror" class="pin-mirror-vertical"/><span>{{ t('垂直镜像') }}</span></van-button></nav>
      <div v-if="mode==='resize'" class="pin-size-editor"><div class="pin-mode-options"><van-button v-for="n in [29,52,58,104]" :key="n" :class="{chosen:widthDraft===n&&heightDraft===n}" @click="widthDraft=heightDraft=n">{{n}} × {{n}}</van-button></div><div class="pin-dimensions"><van-field v-model.number="widthDraft" type="digit" :label="t('宽')"/><van-field v-model.number="heightDraft" type="digit" :label="t('高')"/></div></div>
      <div v-if="mode==='reference'" class="pin-reference-editor"><label v-if="editStep==='opacity'&&reference" class="pin-range">{{t('透明度')}}<van-slider v-model="referenceOpacity" :min="0" :max="1" :step=".01"/></label><div class="pin-mode-options"><van-button class="pin-reference-photo pin-empty-import" @click="refInput?.click()"><img v-if="reference" :src="reference"/><tool-glyph v-else name="import"/><span>{{t(reference?'选择图片':'导入图片')}}</span></van-button><van-button v-if="reference" :class="{chosen:editStep==='opacity'}" @click="editStep=editStep==='opacity'?'photo':'opacity'">{{t('透明度')}}</van-button></div><p>{{t('拖动图片，双指缩放；确认后保存')}}</p></div>
      <div v-if="mode==='import'" class="pin-paged-editor">
        <div class="pin-page-operation" :key="importPage">
          <p v-if="generationError" role="alert">{{ t(generationError) }} <van-button @click="scheduleGeneration">{{ t('重试') }}</van-button></p>
          <template v-else-if="importStage==='generating'"><p>{{ t('正在生成图纸，请稍候…') }}</p></template>
          <template v-else>
            <div v-if="!importPage&&imageType===null" class="pin-image-type-picker">
              <p>{{ t('这张图片属于哪一类？') }}</p>
              <div class="pin-image-type-options">
                <van-button @click="selectImageType('cartoon')"><i class="pin-type-sample pin-type-cartoon"><b></b><b></b><b></b><b></b></i><strong>{{ t('卡通／插画') }}</strong><small>{{ t('小尺寸 · 清晰色块') }}</small></van-button>
                <van-button @click="selectImageType('photo')"><i class="pin-type-sample pin-type-photo"></i><strong>{{ t('照片／写实') }}</strong><small>{{ t('更多格数 · 保留层次') }}</small></van-button>
              </div>
            </div>
            <div v-if="importPage==='rotate'" class="pin-import-control"><div class="pin-mode-options"><van-button @click="rotatePhoto(-1)"><van-icon name="revoke"/>{{ t('逆时针') }}</van-button><van-button @click="rotatePhoto(1)"><van-icon name="replay"/>{{ t('顺时针') }}</van-button></div></div>
            <div v-if="importPage==='detail'" class="pin-import-control"><label class="pin-range">{{ t('图案大小') }} · {{ generatedSize.width }} × {{ generatedSize.height }} {{ t('格') }}<van-slider v-model="targetWidth" :min="Math.min(8,Math.max(project.width,project.height))" :max="Math.max(project.width,project.height)" :step="1"/></label><div class="pin-segments pin-size-presets"><van-button v-for="n in sizePresets" :key="n" :class="{chosen:targetWidth===n}" @click="targetWidth=n">{{ n }}{{ t(' 格') }}</van-button><van-button v-if="Math.max(project.width,project.height)>sizePresets.at(-1)!" @click="targetWidth=Math.max(project.width,project.height)">{{ t('最大') }}</van-button></div><p>{{ t(imageType==='cartoon'?'默认小尺寸，可继续调整':'默认 52 格，保持原图比例') }}</p></div>
            <div v-if="importPage==='colors'" class="pin-import-control"><label class="pin-range">{{ t('用色上限') }} · {{ maxColors }} {{ t('色') }}<van-slider v-model="maxColors" :min="2" :max="211"/></label></div>
            <div v-if="importPage==='style'" class="pin-import-control"><div class="pin-mode-options"><van-button :class="{chosen:imageType==='cartoon'}" @click="selectImageType('cartoon','style')">{{ t('卡通／插画') }}</van-button><van-button :class="{chosen:imageType==='photo'}" @click="selectImageType('photo','style')">{{ t('照片／写实') }}</van-button></div><p>{{ t(imageType==='cartoon'?'保留轮廓、表情和清晰色块':'保留明暗、质感和空间层次') }}</p></div>
            <div v-if="importPage==='background'" class="pin-import-control"><div class="pin-mode-options"><van-button :class="{chosen:!removeBackground}" @click="removeBackground=false">{{ t('保留背景') }}</van-button><van-button :class="{chosen:removeBackground}" @click="removeBackground=true;tolerance=32">{{ t('去除背景') }}</van-button></div></div>
            <div v-if="importPage==='palette'" class="pin-import-control"><div class="pin-mode-options"><van-button :class="{chosen:!allowedMode}" @click="allowedMode=false">{{ t('全部 211 色') }}</van-button><van-button :class="{chosen:allowedMode}" @click="allowedMode=true;importPaletteOpen=true">{{ t('只用我有的颜色') }}</van-button></div><van-button v-if="allowedMode" @click="importPaletteOpen=true">{{ t('已选') }} {{ allowed.length }} {{ t('色 · 点击修改') }}</van-button><p v-else>{{ t('自动从完整色卡匹配最接近的颜色') }}</p></div>
            <div v-if="importPage==='retouch'" class="pin-mode-options"><van-button :class="{chosen:tool==='pencil'}" @click="tool='pencil'">{{ t('画笔') }}</van-button><van-button :class="{chosen:tool==='eraser'}" @click="tool='eraser'">{{ t('橡皮') }}</van-button><van-button @click="importPaletteOpen=true">{{ t(color) }}</van-button><van-button @click="tool='pan'">{{ t('浏览') }}</van-button></div>
            <p v-if="importPage==='preview'">{{ t(candidate?.width) }} × {{ t(candidate?.height) }}{{ t(' 格 · ') }}{{ t(new Set(candidate?.cells.filter(Boolean)).size) }}{{ t(' 色 · 确认后应用到豆板') }}</p>
          </template>
        </div>
        <nav v-if="!singleImportPage&&imageType" v-drag-scroll class="pin-tools pin-parameter-menu" :aria-label="t('导入照片功能')"><van-button v-for="o in [{id:'size',name:'裁剪',icon:'expand-o'},{id:'rotate',name:'旋转',icon:'replay'},{id:'detail',name:'图案大小',icon:'apps-o'},{id:'colors',name:'色数',icon:'brush-o'},{id:'style',name:'图片类型',icon:'photo-o'},{id:'background',name:'背景',icon:'filter-o'},{id:'palette',name:'我的豆色',icon:'apps-o'},...(importStage==='preview'?[{id:'retouch',name:'修整豆子',icon:'edit'},{id:'preview',name:'整体预览',icon:'eye-o'}]:[])]" :key="o.id" :class="{chosen:importPage===o.id,'was-edited':photoChanged(o.id)}" :disabled="importStage==='generating'" @click="importPage=o.id;tool='pan';if(o.id==='size')openCrop();if(o.id==='size'||o.id==='rotate')importStage='photo'"><van-icon :name="o.icon"/><span>{{ t(o.name) }}</span></van-button></nav>
      </div>
      <p v-if="mode==='clear'">{{ t('清空全部拼豆，保留豆板尺寸。确认后可撤销。') }}</p>
    </div>
    <div class="pin-operation-footer"><van-button class="pin-icon-button" :aria-label="t('取消当前操作')" @click="exitMode"><van-icon name="cross"/></van-button><b>{{ t(modeTitle) }}</b><van-button class="pin-icon-button" :class="{'pin-generate-action':mode==='import'&&importStage!=='preview'}" :title="mode==='import'?(importStage==='preview'?'确认应用到豆板':'生成图纸预览'):'保存'" :aria-label="t('保存当前操作')" :disabled="mode==='importPlace'&&(!placement||placementCollision>0)||mode==='recolor'&&focused<0||busy||mode==='import'&&(generating||!image||!imageType||!!generationError||importStage==='preview'&&!!layer?.locked||allowedMode&&!allowed.length)" @click="saveMode"><span v-if="mode==='import'&&importStage!=='preview'">{{ t(generating?'正在生成':'生成图纸') }}</span><van-icon v-else name="success"/></van-button></div>
  </section></Transition>
  <div v-if="cropEditing" class="pin-crop-overlay" role="dialog" :aria-label="t('剪裁照片')"><div class="pin-crop-stage"><photo-crop v-if="imageUrl" v-model="cropDraft" :src="processedPhoto" :square="cropRatio==='square'" active/></div><div class="pin-crop-sheet"><div class="pin-mode-options"><van-button :class="{chosen:cropRatio==='free'}" @click="cropRatio='free'">{{t('自由')}}</van-button><van-button :class="{chosen:cropRatio==='square'}" @click="cropRatio='square'">1:1</van-button></div><div class="pin-operation-footer"><van-button class="pin-icon-button" :aria-label="t('取消剪裁')" @click="cancelCrop"><van-icon name="cross"/></van-button><b>{{ t('剪裁照片') }}</b><van-button class="pin-icon-button" :aria-label="t('确认剪裁')" @click="confirmCrop"><van-icon name="success"/></van-button></div></div></div>
  <div v-if="importPaletteOpen" class="pin-import-palette-overlay" @click.self="importPaletteOpen=false"><section class="pin-palette-sheet" role="dialog" :aria-label="t('导入色号')"><div class="pin-panel-heading"><h2>{{ t(importPage==='retouch'?'修整颜色':'允许使用的色号') }}</h2><van-button class="pin-icon-button" :aria-label="t('关闭导入色卡')" @click="importPaletteOpen=false"><van-icon name="cross"/></van-button></div><van-field v-model="allowedSearch" :placeholder="t('搜索色号')"/><div class="pin-swatches"><van-button v-for="c in allowedPalette" :key="c.code" :class="{chosen:importPage==='retouch'?color===c.code:allowed.includes(c.code)}" @click="importPage==='retouch'?chooseColor(c.code):toggleAllowed(c.code)"><i :style="{'--bead-color':c.hex}"></i><b>{{ t(c.code) }}</b></van-button></div></section></div>
  <input ref="fileInput" hidden type="file" accept="image/png,image/jpeg,image/webp" @change="importPhoto"><input ref="jsonInput" hidden type="file" accept="application/json,.json" @change="importJson"><input ref="refInput" hidden type="file" accept="image/png,image/jpeg,image/webp" @change="importReference">
</div>
</template>
