<script setup lang="ts">
import { computed,ref,onMounted,onUnmounted } from 'vue'
import { t } from '@/shared/i18n'
export type Crop={x:number;y:number;width:number;height:number}
const props=defineProps<{src:string;modelValue:Crop;active:boolean;square?:boolean}>(),emit=defineEmits<{'update:modelValue':[Crop]}>()
const host=ref<HTMLElement|null>(null),frame=ref<HTMLElement|null>(null),ratio=ref(1),bounds=ref({width:1,height:1})
const fit=computed(()=>{const width=Math.min(Math.max(1,bounds.value.width-32),Math.max(1,bounds.value.height-32)*ratio.value);return {width:`${width}px`,height:`${width/ratio.value}px`}})
const box=computed(()=>({left:props.modelValue.x*100+'%',top:props.modelValue.y*100+'%',width:props.modelValue.width*100+'%',height:props.modelValue.height*100+'%'}))
let observer:ResizeObserver|undefined,start:{px:number;py:number;crop:Crop;edge:string;width:number;height:number;id:number}|null=null
onMounted(()=>{if(typeof ResizeObserver==='undefined')return;observer=new ResizeObserver(()=>{if(host.value)bounds.value={width:host.value.clientWidth,height:host.value.clientHeight}});if(host.value)observer.observe(host.value)})
onUnmounted(()=>observer?.disconnect())
function down(e:PointerEvent,edge:string){if(!props.active||!frame.value)return;e.preventDefault();e.stopPropagation();const r=frame.value.getBoundingClientRect();start={px:e.clientX,py:e.clientY,crop:{...props.modelValue},edge,width:r.width,height:r.height,id:e.pointerId};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}
function move(e:PointerEvent){if(!start||e.pointerId!==start.id)return;const c=start.crop,dx=(e.clientX-start.px)/start.width,dy=(e.clientY-start.py)/start.height,clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));let x=c.x,y=c.y,right=c.x+c.width,bottom=c.y+c.height;if(start.edge==='move'){x=clamp(x+dx,0,1-c.width);y=clamp(y+dy,0,1-c.height);right=x+c.width;bottom=y+c.height}else{if(start.edge.includes('w'))x=clamp(x+dx,0,right-.08);if(start.edge.includes('e'))right=clamp(right+dx,x+.08,1);if(start.edge.includes('n'))y=clamp(y+dy,0,bottom-.08);if(start.edge.includes('s'))bottom=clamp(bottom+dy,y+.08,1)}if(props.square&&start.edge!=='move'){const side=Math.min(right-x,(bottom-y)/ratio.value,1-x,(1-y)/ratio.value);right=x+side;bottom=y+side*ratio.value}emit('update:modelValue',{x,y,width:right-x,height:bottom-y})}
</script>
<template><div ref="host" class="pin-crop-host"><div ref="frame" class="pin-crop-frame" :style="fit"><img :src="src" :alt="t('待处理的导入照片')" draggable="false" @load="ratio=($event.target as HTMLImageElement).naturalWidth/($event.target as HTMLImageElement).naturalHeight"/><div v-if="active" class="pin-crop-box" :style="box" @pointerdown="down($event,'move')" @pointermove="move" @pointerup="start=null" @pointercancel="start=null"><i v-for="edge in ['nw','n','ne','e','se','s','sw','w']" :key="edge" :class="edge" @pointerdown="down($event,edge)"/></div></div></div></template>
<style>
.pin-crop-host{width:100%;height:100%;display:grid;place-items:center;overflow:hidden;padding:16px}.pin-crop-frame{position:relative;flex:none;overflow:visible}.pin-crop-frame img{display:block;width:100%;height:100%;object-fit:contain;pointer-events:none}.pin-crop-box{position:absolute;border:2px solid #fffdf6;box-shadow:0 0 0 2000px #35261966;touch-action:none;cursor:move}.pin-crop-box:before,.pin-crop-box:after{content:'';position:absolute;pointer-events:none;inset:33.333% 0;border-block:1px solid #ffffff66}.pin-crop-box:after{inset:0 33.333%;border-block:0;border-inline:1px solid #ffffff66}.pin-crop-box i{position:absolute;width:28px;height:28px;touch-action:none;z-index:2}.pin-crop-box i:after{content:'';position:absolute;inset:9px;border-radius:4px;background:#fffdf6;box-shadow:0 0 0 1px #70594466}.pin-crop-box .nw{left:-14px;top:-14px}.pin-crop-box .ne{right:-14px;top:-14px}.pin-crop-box .sw{left:-14px;bottom:-14px}.pin-crop-box .se{right:-14px;bottom:-14px}.pin-crop-box .n{left:calc(50% - 14px);top:-14px}.pin-crop-box .s{left:calc(50% - 14px);bottom:-14px}.pin-crop-box .w{left:-14px;top:calc(50% - 14px)}.pin-crop-box .e{right:-14px;top:calc(50% - 14px)}.pin-crop-box span{position:absolute;bottom:12px;left:50%;transform:translateX(-50%);white-space:nowrap;background:#705944cc;color:#fff0d5;border-radius:14px;padding:5px 10px;font-size:11px;pointer-events:none}
</style>
